[cooldown]
incompatible-publish-age = "deny"
lockfile-baseline = "ignore"

[registry]
global-min-publish-age = "14 days"

[[allow.package]]
crate = "jay-ash"
min-publish-age = "0"

[[allow.package]]
crate = "uapi"
min-publish-age = "0"

[[allow.package]]
crate = "uapi-proc"
min-publish-age = "0"
