[package]
name = "shaderc-sys"
version = "0.10.1"
edition = "2024"
authors = ["Lei Zhang <antiagainst@gmail.com>", "Mr. Knapp <knappador@gmail.com>"]

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
