pub const MAX_INPUT_EVENT_CODE: usize = 743;

#[derive(Copy, Clone, Debug, Eq, PartialEq, linearize::Linearize)]
#[expect(non_camel_case_types)]
pub enum InputEventCode {
    KEY_ESC,
    KEY_1,
    KEY_2,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,
    KEY_0,
    KEY_MINUS,
    KEY_EQUAL,
    KEY_BACKSPACE,
    KEY_TAB,
    KEY_Q,
    KEY_W,
    KEY_E,
    KEY_R,
    KEY_T,
    KEY_Y,
    KEY_U,
    KEY_I,
    KEY_O,
    KEY_P,
    KEY_LEFTBRACE,
    KEY_RIGHTBRACE,
    KEY_ENTER,
    KEY_LEFTCTRL,
    KEY_A,
    KEY_S,
    KEY_D,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_SEMICOLON,
    KEY_APOSTROPHE,
    KEY_GRAVE,
    KEY_LEFTSHIFT,
    KEY_BACKSLASH,
    KEY_Z,
    KEY_X,
    KEY_C,
    KEY_V,
    KEY_B,
    KEY_N,
    KEY_M,
    KEY_COMMA,
    KEY_DOT,
    KEY_SLASH,
    KEY_RIGHTSHIFT,
    KEY_KPASTERISK,
    KEY_LEFTALT,
    KEY_SPACE,
    KEY_CAPSLOCK,
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_NUMLOCK,
    KEY_SCROLLLOCK,
    KEY_KP7,
    KEY_KP8,
    KEY_KP9,
    KEY_KPMINUS,
    KEY_KP4,
    KEY_KP5,
    KEY_KP6,
    KEY_KPPLUS,
    KEY_KP1,
    KEY_KP2,
    KEY_KP3,
    KEY_KP0,
    KEY_KPDOT,
    KEY_ZENKAKUHANKAKU,
    KEY_102ND,
    KEY_F11,
    KEY_F12,
    KEY_RO,
    KEY_KATAKANA,
    KEY_HIRAGANA,
    KEY_HENKAN,
    KEY_KATAKANAHIRAGANA,
    KEY_MUHENKAN,
    KEY_KPJPCOMMA,
    KEY_KPENTER,
    KEY_RIGHTCTRL,
    KEY_KPSLASH,
    KEY_SYSRQ,
    KEY_RIGHTALT,
    KEY_LINEFEED,
    KEY_HOME,
    KEY_UP,
    KEY_PAGEUP,
    KEY_LEFT,
    KEY_RIGHT,
    KEY_END,
    KEY_DOWN,
    KEY_PAGEDOWN,
    KEY_INSERT,
    KEY_DELETE,
    KEY_MACRO,
    KEY_MUTE,
    KEY_VOLUMEDOWN,
    KEY_VOLUMEUP,
    KEY_POWER,
    KEY_KPEQUAL,
    KEY_KPPLUSMINUS,
    KEY_PAUSE,
    KEY_SCALE,
    KEY_KPCOMMA,
    KEY_HANGEUL,
    KEY_HANJA,
    KEY_YEN,
    KEY_LEFTMETA,
    KEY_RIGHTMETA,
    KEY_COMPOSE,
    KEY_STOP,
    KEY_AGAIN,
    KEY_PROPS,
    KEY_UNDO,
    KEY_FRONT,
    KEY_COPY,
    KEY_OPEN,
    KEY_PASTE,
    KEY_FIND,
    KEY_CUT,
    KEY_HELP,
    KEY_MENU,
    KEY_CALC,
    KEY_SETUP,
    KEY_SLEEP,
    KEY_WAKEUP,
    KEY_FILE,
    KEY_SENDFILE,
    KEY_DELETEFILE,
    KEY_XFER,
    KEY_PROG1,
    KEY_PROG2,
    KEY_WWW,
    KEY_MSDOS,
    KEY_COFFEE,
    KEY_ROTATE_DISPLAY,
    KEY_CYCLEWINDOWS,
    KEY_MAIL,
    KEY_BOOKMARKS,
    KEY_COMPUTER,
    KEY_BACK,
    KEY_FORWARD,
    KEY_CLOSECD,
    KEY_EJECTCD,
    KEY_EJECTCLOSECD,
    KEY_NEXTSONG,
    KEY_PLAYPAUSE,
    KEY_PREVIOUSSONG,
    KEY_STOPCD,
    KEY_RECORD,
    KEY_REWIND,
    KEY_PHONE,
    KEY_ISO,
    KEY_CONFIG,
    KEY_HOMEPAGE,
    KEY_REFRESH,
    KEY_EXIT,
    KEY_MOVE,
    KEY_EDIT,
    KEY_SCROLLUP,
    KEY_SCROLLDOWN,
    KEY_KPLEFTPAREN,
    KEY_KPRIGHTPAREN,
    KEY_NEW,
    KEY_REDO,
    KEY_F13,
    KEY_F14,
    KEY_F15,
    KEY_F16,
    KEY_F17,
    KEY_F18,
    KEY_F19,
    KEY_F20,
    KEY_F21,
    KEY_F22,
    KEY_F23,
    KEY_F24,
    KEY_PLAYCD,
    KEY_PAUSECD,
    KEY_PROG3,
    KEY_PROG4,
    KEY_ALL_APPLICATIONS,
    KEY_SUSPEND,
    KEY_CLOSE,
    KEY_PLAY,
    KEY_FASTFORWARD,
    KEY_BASSBOOST,
    KEY_PRINT,
    KEY_HP,
    KEY_CAMERA,
    KEY_SOUND,
    KEY_QUESTION,
    KEY_EMAIL,
    KEY_CHAT,
    KEY_SEARCH,
    KEY_CONNECT,
    KEY_FINANCE,
    KEY_SPORT,
    KEY_SHOP,
    KEY_ALTERASE,
    KEY_CANCEL,
    KEY_BRIGHTNESSDOWN,
    KEY_BRIGHTNESSUP,
    KEY_MEDIA,
    KEY_SWITCHVIDEOMODE,
    KEY_KBDILLUMTOGGLE,
    KEY_KBDILLUMDOWN,
    KEY_KBDILLUMUP,
    KEY_SEND,
    KEY_REPLY,
    KEY_FORWARDMAIL,
    KEY_SAVE,
    KEY_DOCUMENTS,
    KEY_BATTERY,
    KEY_BLUETOOTH,
    KEY_WLAN,
    KEY_UWB,
    KEY_UNKNOWN,
    KEY_VIDEO_NEXT,
    KEY_VIDEO_PREV,
    KEY_BRIGHTNESS_CYCLE,
    KEY_BRIGHTNESS_AUTO,
    KEY_DISPLAY_OFF,
    KEY_WWAN,
    KEY_RFKILL,
    KEY_MICMUTE,
    BTN_MISC,
    BTN_1,
    BTN_2,
    BTN_3,
    BTN_4,
    BTN_5,
    BTN_6,
    BTN_7,
    BTN_8,
    BTN_9,
    BTN_MOUSE,
    BTN_RIGHT,
    BTN_MIDDLE,
    BTN_SIDE,
    BTN_EXTRA,
    BTN_FORWARD,
    BTN_BACK,
    BTN_TASK,
    BTN_JOYSTICK,
    BTN_THUMB,
    BTN_THUMB2,
    BTN_TOP,
    BTN_TOP2,
    BTN_PINKIE,
    BTN_BASE,
    BTN_BASE2,
    BTN_BASE3,
    BTN_BASE4,
    BTN_BASE5,
    BTN_BASE6,
    BTN_DEAD,
    BTN_GAMEPAD,
    BTN_EAST,
    BTN_C,
    BTN_NORTH,
    BTN_WEST,
    BTN_Z,
    BTN_TL,
    BTN_TR,
    BTN_TL2,
    BTN_TR2,
    BTN_SELECT,
    BTN_START,
    BTN_MODE,
    BTN_THUMBL,
    BTN_THUMBR,
    BTN_DIGI,
    BTN_TOOL_RUBBER,
    BTN_TOOL_BRUSH,
    BTN_TOOL_PENCIL,
    BTN_TOOL_AIRBRUSH,
    BTN_TOOL_FINGER,
    BTN_TOOL_MOUSE,
    BTN_TOOL_LENS,
    BTN_TOOL_QUINTTAP,
    BTN_STYLUS3,
    BTN_TOUCH,
    BTN_STYLUS,
    BTN_STYLUS2,
    BTN_TOOL_DOUBLETAP,
    BTN_TOOL_TRIPLETAP,
    BTN_TOOL_QUADTAP,
    BTN_WHEEL,
    BTN_GEAR_UP,
    KEY_OK,
    KEY_SELECT,
    KEY_GOTO,
    KEY_CLEAR,
    KEY_POWER2,
    KEY_OPTION,
    KEY_INFO,
    KEY_TIME,
    KEY_VENDOR,
    KEY_ARCHIVE,
    KEY_PROGRAM,
    KEY_CHANNEL,
    KEY_FAVORITES,
    KEY_EPG,
    KEY_PVR,
    KEY_MHP,
    KEY_LANGUAGE,
    KEY_TITLE,
    KEY_SUBTITLE,
    KEY_ANGLE,
    KEY_FULL_SCREEN,
    KEY_MODE,
    KEY_KEYBOARD,
    KEY_ASPECT_RATIO,
    KEY_PC,
    KEY_TV,
    KEY_TV2,
    KEY_VCR,
    KEY_VCR2,
    KEY_SAT,
    KEY_SAT2,
    KEY_CD,
    KEY_TAPE,
    KEY_RADIO,
    KEY_TUNER,
    KEY_PLAYER,
    KEY_TEXT,
    KEY_DVD,
    KEY_AUX,
    KEY_MP3,
    KEY_AUDIO,
    KEY_VIDEO,
    KEY_DIRECTORY,
    KEY_LIST,
    KEY_MEMO,
    KEY_CALENDAR,
    KEY_RED,
    KEY_GREEN,
    KEY_YELLOW,
    KEY_BLUE,
    KEY_CHANNELUP,
    KEY_CHANNELDOWN,
    KEY_FIRST,
    KEY_LAST,
    KEY_AB,
    KEY_NEXT,
    KEY_RESTART,
    KEY_SLOW,
    KEY_SHUFFLE,
    KEY_BREAK,
    KEY_PREVIOUS,
    KEY_DIGITS,
    KEY_TEEN,
    KEY_TWEN,
    KEY_VIDEOPHONE,
    KEY_GAMES,
    KEY_ZOOMIN,
    KEY_ZOOMOUT,
    KEY_ZOOMRESET,
    KEY_WORDPROCESSOR,
    KEY_EDITOR,
    KEY_SPREADSHEET,
    KEY_GRAPHICSEDITOR,
    KEY_PRESENTATION,
    KEY_DATABASE,
    KEY_NEWS,
    KEY_VOICEMAIL,
    KEY_ADDRESSBOOK,
    KEY_MESSENGER,
    KEY_DISPLAYTOGGLE,
    KEY_SPELLCHECK,
    KEY_LOGOFF,
    KEY_DOLLAR,
    KEY_EURO,
    KEY_FRAMEBACK,
    KEY_FRAMEFORWARD,
    KEY_CONTEXT_MENU,
    KEY_MEDIA_REPEAT,
    KEY_10CHANNELSUP,
    KEY_10CHANNELSDOWN,
    KEY_IMAGES,
    KEY_NOTIFICATION_CENTER,
    KEY_PICKUP_PHONE,
    KEY_HANGUP_PHONE,
    KEY_LINK_PHONE,
    KEY_DEL_EOL,
    KEY_DEL_EOS,
    KEY_INS_LINE,
    KEY_DEL_LINE,
    KEY_FN,
    KEY_FN_ESC,
    KEY_FN_F1,
    KEY_FN_F2,
    KEY_FN_F3,
    KEY_FN_F4,
    KEY_FN_F5,
    KEY_FN_F6,
    KEY_FN_F7,
    KEY_FN_F8,
    KEY_FN_F9,
    KEY_FN_F10,
    KEY_FN_F11,
    KEY_FN_F12,
    KEY_FN_1,
    KEY_FN_2,
    KEY_FN_D,
    KEY_FN_E,
    KEY_FN_F,
    KEY_FN_S,
    KEY_FN_B,
    KEY_FN_RIGHT_SHIFT,
    KEY_BRL_DOT1,
    KEY_BRL_DOT2,
    KEY_BRL_DOT3,
    KEY_BRL_DOT4,
    KEY_BRL_DOT5,
    KEY_BRL_DOT6,
    KEY_BRL_DOT7,
    KEY_BRL_DOT8,
    KEY_BRL_DOT9,
    KEY_BRL_DOT10,
    KEY_NUMERIC_0,
    KEY_NUMERIC_1,
    KEY_NUMERIC_2,
    KEY_NUMERIC_3,
    KEY_NUMERIC_4,
    KEY_NUMERIC_5,
    KEY_NUMERIC_6,
    KEY_NUMERIC_7,
    KEY_NUMERIC_8,
    KEY_NUMERIC_9,
    KEY_NUMERIC_STAR,
    KEY_NUMERIC_POUND,
    KEY_NUMERIC_A,
    KEY_NUMERIC_B,
    KEY_NUMERIC_C,
    KEY_NUMERIC_D,
    KEY_CAMERA_FOCUS,
    KEY_WPS_BUTTON,
    KEY_TOUCHPAD_TOGGLE,
    KEY_TOUCHPAD_ON,
    KEY_TOUCHPAD_OFF,
    KEY_CAMERA_ZOOMIN,
    KEY_CAMERA_ZOOMOUT,
    KEY_CAMERA_UP,
    KEY_CAMERA_DOWN,
    KEY_CAMERA_LEFT,
    KEY_CAMERA_RIGHT,
    KEY_ATTENDANT_ON,
    KEY_ATTENDANT_OFF,
    KEY_ATTENDANT_TOGGLE,
    KEY_LIGHTS_TOGGLE,
    BTN_DPAD_UP,
    BTN_DPAD_DOWN,
    BTN_DPAD_LEFT,
    BTN_DPAD_RIGHT,
    BTN_GRIPL,
    BTN_GRIPR,
    BTN_GRIPL2,
    BTN_GRIPR2,
    KEY_ALS_TOGGLE,
    KEY_ROTATE_LOCK_TOGGLE,
    KEY_REFRESH_RATE_TOGGLE,
    KEY_BUTTONCONFIG,
    KEY_TASKMANAGER,
    KEY_JOURNAL,
    KEY_CONTROLPANEL,
    KEY_APPSELECT,
    KEY_SCREENSAVER,
    KEY_VOICECOMMAND,
    KEY_ASSISTANT,
    KEY_KBD_LAYOUT_NEXT,
    KEY_EMOJI_PICKER,
    KEY_DICTATE,
    KEY_CAMERA_ACCESS_ENABLE,
    KEY_CAMERA_ACCESS_DISABLE,
    KEY_CAMERA_ACCESS_TOGGLE,
    KEY_ACCESSIBILITY,
    KEY_DO_NOT_DISTURB,
    KEY_BRIGHTNESS_MIN,
    KEY_BRIGHTNESS_MAX,
    KEY_EPRIVACY_SCREEN_ON,
    KEY_EPRIVACY_SCREEN_OFF,
    KEY_ACTION_ON_SELECTION,
    KEY_CONTEXTUAL_INSERT,
    KEY_CONTEXTUAL_QUERY,
    KEY_KBDINPUTASSIST_PREV,
    KEY_KBDINPUTASSIST_NEXT,
    KEY_KBDINPUTASSIST_PREVGROUP,
    KEY_KBDINPUTASSIST_NEXTGROUP,
    KEY_KBDINPUTASSIST_ACCEPT,
    KEY_KBDINPUTASSIST_CANCEL,
    KEY_RIGHT_UP,
    KEY_RIGHT_DOWN,
    KEY_LEFT_UP,
    KEY_LEFT_DOWN,
    KEY_ROOT_MENU,
    KEY_MEDIA_TOP_MENU,
    KEY_NUMERIC_11,
    KEY_NUMERIC_12,
    KEY_AUDIO_DESC,
    KEY_3D_MODE,
    KEY_NEXT_FAVORITE,
    KEY_STOP_RECORD,
    KEY_PAUSE_RECORD,
    KEY_VOD,
    KEY_UNMUTE,
    KEY_FASTREVERSE,
    KEY_SLOWREVERSE,
    KEY_DATA,
    KEY_ONSCREEN_KEYBOARD,
    KEY_PRIVACY_SCREEN_TOGGLE,
    KEY_SELECTIVE_SCREENSHOT,
    KEY_NEXT_ELEMENT,
    KEY_PREVIOUS_ELEMENT,
    KEY_AUTOPILOT_ENGAGE_TOGGLE,
    KEY_MARK_WAYPOINT,
    KEY_SOS,
    KEY_NAV_CHART,
    KEY_FISHING_CHART,
    KEY_SINGLE_RANGE_RADAR,
    KEY_DUAL_RANGE_RADAR,
    KEY_RADAR_OVERLAY,
    KEY_TRADITIONAL_SONAR,
    KEY_CLEARVU_SONAR,
    KEY_SIDEVU_SONAR,
    KEY_NAV_INFO,
    KEY_BRIGHTNESS_MENU,
    KEY_MACRO1,
    KEY_MACRO2,
    KEY_MACRO3,
    KEY_MACRO4,
    KEY_MACRO5,
    KEY_MACRO6,
    KEY_MACRO7,
    KEY_MACRO8,
    KEY_MACRO9,
    KEY_MACRO10,
    KEY_MACRO11,
    KEY_MACRO12,
    KEY_MACRO13,
    KEY_MACRO14,
    KEY_MACRO15,
    KEY_MACRO16,
    KEY_MACRO17,
    KEY_MACRO18,
    KEY_MACRO19,
    KEY_MACRO20,
    KEY_MACRO21,
    KEY_MACRO22,
    KEY_MACRO23,
    KEY_MACRO24,
    KEY_MACRO25,
    KEY_MACRO26,
    KEY_MACRO27,
    KEY_MACRO28,
    KEY_MACRO29,
    KEY_MACRO30,
    KEY_MACRO_RECORD_START,
    KEY_MACRO_RECORD_STOP,
    KEY_MACRO_PRESET_CYCLE,
    KEY_MACRO_PRESET1,
    KEY_MACRO_PRESET2,
    KEY_MACRO_PRESET3,
    KEY_KBD_LCD_MENU1,
    KEY_KBD_LCD_MENU2,
    KEY_KBD_LCD_MENU3,
    KEY_KBD_LCD_MENU4,
    KEY_KBD_LCD_MENU5,
    KEY_PERFORMANCE,
    BTN_TRIGGER_HAPPY,
    BTN_TRIGGER_HAPPY2,
    BTN_TRIGGER_HAPPY3,
    BTN_TRIGGER_HAPPY4,
    BTN_TRIGGER_HAPPY5,
    BTN_TRIGGER_HAPPY6,
    BTN_TRIGGER_HAPPY7,
    BTN_TRIGGER_HAPPY8,
    BTN_TRIGGER_HAPPY9,
    BTN_TRIGGER_HAPPY10,
    BTN_TRIGGER_HAPPY11,
    BTN_TRIGGER_HAPPY12,
    BTN_TRIGGER_HAPPY13,
    BTN_TRIGGER_HAPPY14,
    BTN_TRIGGER_HAPPY15,
    BTN_TRIGGER_HAPPY16,
    BTN_TRIGGER_HAPPY17,
    BTN_TRIGGER_HAPPY18,
    BTN_TRIGGER_HAPPY19,
    BTN_TRIGGER_HAPPY20,
    BTN_TRIGGER_HAPPY21,
    BTN_TRIGGER_HAPPY22,
    BTN_TRIGGER_HAPPY23,
    BTN_TRIGGER_HAPPY24,
    BTN_TRIGGER_HAPPY25,
    BTN_TRIGGER_HAPPY26,
    BTN_TRIGGER_HAPPY27,
    BTN_TRIGGER_HAPPY28,
    BTN_TRIGGER_HAPPY29,
    BTN_TRIGGER_HAPPY30,
    BTN_TRIGGER_HAPPY31,
    BTN_TRIGGER_HAPPY32,
    BTN_TRIGGER_HAPPY33,
    BTN_TRIGGER_HAPPY34,
    BTN_TRIGGER_HAPPY35,
    BTN_TRIGGER_HAPPY36,
    BTN_TRIGGER_HAPPY37,
    BTN_TRIGGER_HAPPY38,
    BTN_TRIGGER_HAPPY39,
    BTN_TRIGGER_HAPPY40,
}

impl InputEventCode {
    pub fn raw(self) -> u32 {
        match self {
            Self::KEY_ESC => 1,
            Self::KEY_1 => 2,
            Self::KEY_2 => 3,
            Self::KEY_3 => 4,
            Self::KEY_4 => 5,
            Self::KEY_5 => 6,
            Self::KEY_6 => 7,
            Self::KEY_7 => 8,
            Self::KEY_8 => 9,
            Self::KEY_9 => 10,
            Self::KEY_0 => 11,
            Self::KEY_MINUS => 12,
            Self::KEY_EQUAL => 13,
            Self::KEY_BACKSPACE => 14,
            Self::KEY_TAB => 15,
            Self::KEY_Q => 16,
            Self::KEY_W => 17,
            Self::KEY_E => 18,
            Self::KEY_R => 19,
            Self::KEY_T => 20,
            Self::KEY_Y => 21,
            Self::KEY_U => 22,
            Self::KEY_I => 23,
            Self::KEY_O => 24,
            Self::KEY_P => 25,
            Self::KEY_LEFTBRACE => 26,
            Self::KEY_RIGHTBRACE => 27,
            Self::KEY_ENTER => 28,
            Self::KEY_LEFTCTRL => 29,
            Self::KEY_A => 30,
            Self::KEY_S => 31,
            Self::KEY_D => 32,
            Self::KEY_F => 33,
            Self::KEY_G => 34,
            Self::KEY_H => 35,
            Self::KEY_J => 36,
            Self::KEY_K => 37,
            Self::KEY_L => 38,
            Self::KEY_SEMICOLON => 39,
            Self::KEY_APOSTROPHE => 40,
            Self::KEY_GRAVE => 41,
            Self::KEY_LEFTSHIFT => 42,
            Self::KEY_BACKSLASH => 43,
            Self::KEY_Z => 44,
            Self::KEY_X => 45,
            Self::KEY_C => 46,
            Self::KEY_V => 47,
            Self::KEY_B => 48,
            Self::KEY_N => 49,
            Self::KEY_M => 50,
            Self::KEY_COMMA => 51,
            Self::KEY_DOT => 52,
            Self::KEY_SLASH => 53,
            Self::KEY_RIGHTSHIFT => 54,
            Self::KEY_KPASTERISK => 55,
            Self::KEY_LEFTALT => 56,
            Self::KEY_SPACE => 57,
            Self::KEY_CAPSLOCK => 58,
            Self::KEY_F1 => 59,
            Self::KEY_F2 => 60,
            Self::KEY_F3 => 61,
            Self::KEY_F4 => 62,
            Self::KEY_F5 => 63,
            Self::KEY_F6 => 64,
            Self::KEY_F7 => 65,
            Self::KEY_F8 => 66,
            Self::KEY_F9 => 67,
            Self::KEY_F10 => 68,
            Self::KEY_NUMLOCK => 69,
            Self::KEY_SCROLLLOCK => 70,
            Self::KEY_KP7 => 71,
            Self::KEY_KP8 => 72,
            Self::KEY_KP9 => 73,
            Self::KEY_KPMINUS => 74,
            Self::KEY_KP4 => 75,
            Self::KEY_KP5 => 76,
            Self::KEY_KP6 => 77,
            Self::KEY_KPPLUS => 78,
            Self::KEY_KP1 => 79,
            Self::KEY_KP2 => 80,
            Self::KEY_KP3 => 81,
            Self::KEY_KP0 => 82,
            Self::KEY_KPDOT => 83,
            Self::KEY_ZENKAKUHANKAKU => 85,
            Self::KEY_102ND => 86,
            Self::KEY_F11 => 87,
            Self::KEY_F12 => 88,
            Self::KEY_RO => 89,
            Self::KEY_KATAKANA => 90,
            Self::KEY_HIRAGANA => 91,
            Self::KEY_HENKAN => 92,
            Self::KEY_KATAKANAHIRAGANA => 93,
            Self::KEY_MUHENKAN => 94,
            Self::KEY_KPJPCOMMA => 95,
            Self::KEY_KPENTER => 96,
            Self::KEY_RIGHTCTRL => 97,
            Self::KEY_KPSLASH => 98,
            Self::KEY_SYSRQ => 99,
            Self::KEY_RIGHTALT => 100,
            Self::KEY_LINEFEED => 101,
            Self::KEY_HOME => 102,
            Self::KEY_UP => 103,
            Self::KEY_PAGEUP => 104,
            Self::KEY_LEFT => 105,
            Self::KEY_RIGHT => 106,
            Self::KEY_END => 107,
            Self::KEY_DOWN => 108,
            Self::KEY_PAGEDOWN => 109,
            Self::KEY_INSERT => 110,
            Self::KEY_DELETE => 111,
            Self::KEY_MACRO => 112,
            Self::KEY_MUTE => 113,
            Self::KEY_VOLUMEDOWN => 114,
            Self::KEY_VOLUMEUP => 115,
            Self::KEY_POWER => 116,
            Self::KEY_KPEQUAL => 117,
            Self::KEY_KPPLUSMINUS => 118,
            Self::KEY_PAUSE => 119,
            Self::KEY_SCALE => 120,
            Self::KEY_KPCOMMA => 121,
            Self::KEY_HANGEUL => 122,
            Self::KEY_HANJA => 123,
            Self::KEY_YEN => 124,
            Self::KEY_LEFTMETA => 125,
            Self::KEY_RIGHTMETA => 126,
            Self::KEY_COMPOSE => 127,
            Self::KEY_STOP => 128,
            Self::KEY_AGAIN => 129,
            Self::KEY_PROPS => 130,
            Self::KEY_UNDO => 131,
            Self::KEY_FRONT => 132,
            Self::KEY_COPY => 133,
            Self::KEY_OPEN => 134,
            Self::KEY_PASTE => 135,
            Self::KEY_FIND => 136,
            Self::KEY_CUT => 137,
            Self::KEY_HELP => 138,
            Self::KEY_MENU => 139,
            Self::KEY_CALC => 140,
            Self::KEY_SETUP => 141,
            Self::KEY_SLEEP => 142,
            Self::KEY_WAKEUP => 143,
            Self::KEY_FILE => 144,
            Self::KEY_SENDFILE => 145,
            Self::KEY_DELETEFILE => 146,
            Self::KEY_XFER => 147,
            Self::KEY_PROG1 => 148,
            Self::KEY_PROG2 => 149,
            Self::KEY_WWW => 150,
            Self::KEY_MSDOS => 151,
            Self::KEY_COFFEE => 152,
            Self::KEY_ROTATE_DISPLAY => 153,
            Self::KEY_CYCLEWINDOWS => 154,
            Self::KEY_MAIL => 155,
            Self::KEY_BOOKMARKS => 156,
            Self::KEY_COMPUTER => 157,
            Self::KEY_BACK => 158,
            Self::KEY_FORWARD => 159,
            Self::KEY_CLOSECD => 160,
            Self::KEY_EJECTCD => 161,
            Self::KEY_EJECTCLOSECD => 162,
            Self::KEY_NEXTSONG => 163,
            Self::KEY_PLAYPAUSE => 164,
            Self::KEY_PREVIOUSSONG => 165,
            Self::KEY_STOPCD => 166,
            Self::KEY_RECORD => 167,
            Self::KEY_REWIND => 168,
            Self::KEY_PHONE => 169,
            Self::KEY_ISO => 170,
            Self::KEY_CONFIG => 171,
            Self::KEY_HOMEPAGE => 172,
            Self::KEY_REFRESH => 173,
            Self::KEY_EXIT => 174,
            Self::KEY_MOVE => 175,
            Self::KEY_EDIT => 176,
            Self::KEY_SCROLLUP => 177,
            Self::KEY_SCROLLDOWN => 178,
            Self::KEY_KPLEFTPAREN => 179,
            Self::KEY_KPRIGHTPAREN => 180,
            Self::KEY_NEW => 181,
            Self::KEY_REDO => 182,
            Self::KEY_F13 => 183,
            Self::KEY_F14 => 184,
            Self::KEY_F15 => 185,
            Self::KEY_F16 => 186,
            Self::KEY_F17 => 187,
            Self::KEY_F18 => 188,
            Self::KEY_F19 => 189,
            Self::KEY_F20 => 190,
            Self::KEY_F21 => 191,
            Self::KEY_F22 => 192,
            Self::KEY_F23 => 193,
            Self::KEY_F24 => 194,
            Self::KEY_PLAYCD => 200,
            Self::KEY_PAUSECD => 201,
            Self::KEY_PROG3 => 202,
            Self::KEY_PROG4 => 203,
            Self::KEY_ALL_APPLICATIONS => 204,
            Self::KEY_SUSPEND => 205,
            Self::KEY_CLOSE => 206,
            Self::KEY_PLAY => 207,
            Self::KEY_FASTFORWARD => 208,
            Self::KEY_BASSBOOST => 209,
            Self::KEY_PRINT => 210,
            Self::KEY_HP => 211,
            Self::KEY_CAMERA => 212,
            Self::KEY_SOUND => 213,
            Self::KEY_QUESTION => 214,
            Self::KEY_EMAIL => 215,
            Self::KEY_CHAT => 216,
            Self::KEY_SEARCH => 217,
            Self::KEY_CONNECT => 218,
            Self::KEY_FINANCE => 219,
            Self::KEY_SPORT => 220,
            Self::KEY_SHOP => 221,
            Self::KEY_ALTERASE => 222,
            Self::KEY_CANCEL => 223,
            Self::KEY_BRIGHTNESSDOWN => 224,
            Self::KEY_BRIGHTNESSUP => 225,
            Self::KEY_MEDIA => 226,
            Self::KEY_SWITCHVIDEOMODE => 227,
            Self::KEY_KBDILLUMTOGGLE => 228,
            Self::KEY_KBDILLUMDOWN => 229,
            Self::KEY_KBDILLUMUP => 230,
            Self::KEY_SEND => 231,
            Self::KEY_REPLY => 232,
            Self::KEY_FORWARDMAIL => 233,
            Self::KEY_SAVE => 234,
            Self::KEY_DOCUMENTS => 235,
            Self::KEY_BATTERY => 236,
            Self::KEY_BLUETOOTH => 237,
            Self::KEY_WLAN => 238,
            Self::KEY_UWB => 239,
            Self::KEY_UNKNOWN => 240,
            Self::KEY_VIDEO_NEXT => 241,
            Self::KEY_VIDEO_PREV => 242,
            Self::KEY_BRIGHTNESS_CYCLE => 243,
            Self::KEY_BRIGHTNESS_AUTO => 244,
            Self::KEY_DISPLAY_OFF => 245,
            Self::KEY_WWAN => 246,
            Self::KEY_RFKILL => 247,
            Self::KEY_MICMUTE => 248,
            Self::BTN_MISC => 256,
            Self::BTN_1 => 257,
            Self::BTN_2 => 258,
            Self::BTN_3 => 259,
            Self::BTN_4 => 260,
            Self::BTN_5 => 261,
            Self::BTN_6 => 262,
            Self::BTN_7 => 263,
            Self::BTN_8 => 264,
            Self::BTN_9 => 265,
            Self::BTN_MOUSE => 272,
            Self::BTN_RIGHT => 273,
            Self::BTN_MIDDLE => 274,
            Self::BTN_SIDE => 275,
            Self::BTN_EXTRA => 276,
            Self::BTN_FORWARD => 277,
            Self::BTN_BACK => 278,
            Self::BTN_TASK => 279,
            Self::BTN_JOYSTICK => 288,
            Self::BTN_THUMB => 289,
            Self::BTN_THUMB2 => 290,
            Self::BTN_TOP => 291,
            Self::BTN_TOP2 => 292,
            Self::BTN_PINKIE => 293,
            Self::BTN_BASE => 294,
            Self::BTN_BASE2 => 295,
            Self::BTN_BASE3 => 296,
            Self::BTN_BASE4 => 297,
            Self::BTN_BASE5 => 298,
            Self::BTN_BASE6 => 299,
            Self::BTN_DEAD => 303,
            Self::BTN_GAMEPAD => 304,
            Self::BTN_EAST => 305,
            Self::BTN_C => 306,
            Self::BTN_NORTH => 307,
            Self::BTN_WEST => 308,
            Self::BTN_Z => 309,
            Self::BTN_TL => 310,
            Self::BTN_TR => 311,
            Self::BTN_TL2 => 312,
            Self::BTN_TR2 => 313,
            Self::BTN_SELECT => 314,
            Self::BTN_START => 315,
            Self::BTN_MODE => 316,
            Self::BTN_THUMBL => 317,
            Self::BTN_THUMBR => 318,
            Self::BTN_DIGI => 320,
            Self::BTN_TOOL_RUBBER => 321,
            Self::BTN_TOOL_BRUSH => 322,
            Self::BTN_TOOL_PENCIL => 323,
            Self::BTN_TOOL_AIRBRUSH => 324,
            Self::BTN_TOOL_FINGER => 325,
            Self::BTN_TOOL_MOUSE => 326,
            Self::BTN_TOOL_LENS => 327,
            Self::BTN_TOOL_QUINTTAP => 328,
            Self::BTN_STYLUS3 => 329,
            Self::BTN_TOUCH => 330,
            Self::BTN_STYLUS => 331,
            Self::BTN_STYLUS2 => 332,
            Self::BTN_TOOL_DOUBLETAP => 333,
            Self::BTN_TOOL_TRIPLETAP => 334,
            Self::BTN_TOOL_QUADTAP => 335,
            Self::BTN_WHEEL => 336,
            Self::BTN_GEAR_UP => 337,
            Self::KEY_OK => 352,
            Self::KEY_SELECT => 353,
            Self::KEY_GOTO => 354,
            Self::KEY_CLEAR => 355,
            Self::KEY_POWER2 => 356,
            Self::KEY_OPTION => 357,
            Self::KEY_INFO => 358,
            Self::KEY_TIME => 359,
            Self::KEY_VENDOR => 360,
            Self::KEY_ARCHIVE => 361,
            Self::KEY_PROGRAM => 362,
            Self::KEY_CHANNEL => 363,
            Self::KEY_FAVORITES => 364,
            Self::KEY_EPG => 365,
            Self::KEY_PVR => 366,
            Self::KEY_MHP => 367,
            Self::KEY_LANGUAGE => 368,
            Self::KEY_TITLE => 369,
            Self::KEY_SUBTITLE => 370,
            Self::KEY_ANGLE => 371,
            Self::KEY_FULL_SCREEN => 372,
            Self::KEY_MODE => 373,
            Self::KEY_KEYBOARD => 374,
            Self::KEY_ASPECT_RATIO => 375,
            Self::KEY_PC => 376,
            Self::KEY_TV => 377,
            Self::KEY_TV2 => 378,
            Self::KEY_VCR => 379,
            Self::KEY_VCR2 => 380,
            Self::KEY_SAT => 381,
            Self::KEY_SAT2 => 382,
            Self::KEY_CD => 383,
            Self::KEY_TAPE => 384,
            Self::KEY_RADIO => 385,
            Self::KEY_TUNER => 386,
            Self::KEY_PLAYER => 387,
            Self::KEY_TEXT => 388,
            Self::KEY_DVD => 389,
            Self::KEY_AUX => 390,
            Self::KEY_MP3 => 391,
            Self::KEY_AUDIO => 392,
            Self::KEY_VIDEO => 393,
            Self::KEY_DIRECTORY => 394,
            Self::KEY_LIST => 395,
            Self::KEY_MEMO => 396,
            Self::KEY_CALENDAR => 397,
            Self::KEY_RED => 398,
            Self::KEY_GREEN => 399,
            Self::KEY_YELLOW => 400,
            Self::KEY_BLUE => 401,
            Self::KEY_CHANNELUP => 402,
            Self::KEY_CHANNELDOWN => 403,
            Self::KEY_FIRST => 404,
            Self::KEY_LAST => 405,
            Self::KEY_AB => 406,
            Self::KEY_NEXT => 407,
            Self::KEY_RESTART => 408,
            Self::KEY_SLOW => 409,
            Self::KEY_SHUFFLE => 410,
            Self::KEY_BREAK => 411,
            Self::KEY_PREVIOUS => 412,
            Self::KEY_DIGITS => 413,
            Self::KEY_TEEN => 414,
            Self::KEY_TWEN => 415,
            Self::KEY_VIDEOPHONE => 416,
            Self::KEY_GAMES => 417,
            Self::KEY_ZOOMIN => 418,
            Self::KEY_ZOOMOUT => 419,
            Self::KEY_ZOOMRESET => 420,
            Self::KEY_WORDPROCESSOR => 421,
            Self::KEY_EDITOR => 422,
            Self::KEY_SPREADSHEET => 423,
            Self::KEY_GRAPHICSEDITOR => 424,
            Self::KEY_PRESENTATION => 425,
            Self::KEY_DATABASE => 426,
            Self::KEY_NEWS => 427,
            Self::KEY_VOICEMAIL => 428,
            Self::KEY_ADDRESSBOOK => 429,
            Self::KEY_MESSENGER => 430,
            Self::KEY_DISPLAYTOGGLE => 431,
            Self::KEY_SPELLCHECK => 432,
            Self::KEY_LOGOFF => 433,
            Self::KEY_DOLLAR => 434,
            Self::KEY_EURO => 435,
            Self::KEY_FRAMEBACK => 436,
            Self::KEY_FRAMEFORWARD => 437,
            Self::KEY_CONTEXT_MENU => 438,
            Self::KEY_MEDIA_REPEAT => 439,
            Self::KEY_10CHANNELSUP => 440,
            Self::KEY_10CHANNELSDOWN => 441,
            Self::KEY_IMAGES => 442,
            Self::KEY_NOTIFICATION_CENTER => 444,
            Self::KEY_PICKUP_PHONE => 445,
            Self::KEY_HANGUP_PHONE => 446,
            Self::KEY_LINK_PHONE => 447,
            Self::KEY_DEL_EOL => 448,
            Self::KEY_DEL_EOS => 449,
            Self::KEY_INS_LINE => 450,
            Self::KEY_DEL_LINE => 451,
            Self::KEY_FN => 464,
            Self::KEY_FN_ESC => 465,
            Self::KEY_FN_F1 => 466,
            Self::KEY_FN_F2 => 467,
            Self::KEY_FN_F3 => 468,
            Self::KEY_FN_F4 => 469,
            Self::KEY_FN_F5 => 470,
            Self::KEY_FN_F6 => 471,
            Self::KEY_FN_F7 => 472,
            Self::KEY_FN_F8 => 473,
            Self::KEY_FN_F9 => 474,
            Self::KEY_FN_F10 => 475,
            Self::KEY_FN_F11 => 476,
            Self::KEY_FN_F12 => 477,
            Self::KEY_FN_1 => 478,
            Self::KEY_FN_2 => 479,
            Self::KEY_FN_D => 480,
            Self::KEY_FN_E => 481,
            Self::KEY_FN_F => 482,
            Self::KEY_FN_S => 483,
            Self::KEY_FN_B => 484,
            Self::KEY_FN_RIGHT_SHIFT => 485,
            Self::KEY_BRL_DOT1 => 497,
            Self::KEY_BRL_DOT2 => 498,
            Self::KEY_BRL_DOT3 => 499,
            Self::KEY_BRL_DOT4 => 500,
            Self::KEY_BRL_DOT5 => 501,
            Self::KEY_BRL_DOT6 => 502,
            Self::KEY_BRL_DOT7 => 503,
            Self::KEY_BRL_DOT8 => 504,
            Self::KEY_BRL_DOT9 => 505,
            Self::KEY_BRL_DOT10 => 506,
            Self::KEY_NUMERIC_0 => 512,
            Self::KEY_NUMERIC_1 => 513,
            Self::KEY_NUMERIC_2 => 514,
            Self::KEY_NUMERIC_3 => 515,
            Self::KEY_NUMERIC_4 => 516,
            Self::KEY_NUMERIC_5 => 517,
            Self::KEY_NUMERIC_6 => 518,
            Self::KEY_NUMERIC_7 => 519,
            Self::KEY_NUMERIC_8 => 520,
            Self::KEY_NUMERIC_9 => 521,
            Self::KEY_NUMERIC_STAR => 522,
            Self::KEY_NUMERIC_POUND => 523,
            Self::KEY_NUMERIC_A => 524,
            Self::KEY_NUMERIC_B => 525,
            Self::KEY_NUMERIC_C => 526,
            Self::KEY_NUMERIC_D => 527,
            Self::KEY_CAMERA_FOCUS => 528,
            Self::KEY_WPS_BUTTON => 529,
            Self::KEY_TOUCHPAD_TOGGLE => 530,
            Self::KEY_TOUCHPAD_ON => 531,
            Self::KEY_TOUCHPAD_OFF => 532,
            Self::KEY_CAMERA_ZOOMIN => 533,
            Self::KEY_CAMERA_ZOOMOUT => 534,
            Self::KEY_CAMERA_UP => 535,
            Self::KEY_CAMERA_DOWN => 536,
            Self::KEY_CAMERA_LEFT => 537,
            Self::KEY_CAMERA_RIGHT => 538,
            Self::KEY_ATTENDANT_ON => 539,
            Self::KEY_ATTENDANT_OFF => 540,
            Self::KEY_ATTENDANT_TOGGLE => 541,
            Self::KEY_LIGHTS_TOGGLE => 542,
            Self::BTN_DPAD_UP => 544,
            Self::BTN_DPAD_DOWN => 545,
            Self::BTN_DPAD_LEFT => 546,
            Self::BTN_DPAD_RIGHT => 547,
            Self::BTN_GRIPL => 548,
            Self::BTN_GRIPR => 549,
            Self::BTN_GRIPL2 => 550,
            Self::BTN_GRIPR2 => 551,
            Self::KEY_ALS_TOGGLE => 560,
            Self::KEY_ROTATE_LOCK_TOGGLE => 561,
            Self::KEY_REFRESH_RATE_TOGGLE => 562,
            Self::KEY_BUTTONCONFIG => 576,
            Self::KEY_TASKMANAGER => 577,
            Self::KEY_JOURNAL => 578,
            Self::KEY_CONTROLPANEL => 579,
            Self::KEY_APPSELECT => 580,
            Self::KEY_SCREENSAVER => 581,
            Self::KEY_VOICECOMMAND => 582,
            Self::KEY_ASSISTANT => 583,
            Self::KEY_KBD_LAYOUT_NEXT => 584,
            Self::KEY_EMOJI_PICKER => 585,
            Self::KEY_DICTATE => 586,
            Self::KEY_CAMERA_ACCESS_ENABLE => 587,
            Self::KEY_CAMERA_ACCESS_DISABLE => 588,
            Self::KEY_CAMERA_ACCESS_TOGGLE => 589,
            Self::KEY_ACCESSIBILITY => 590,
            Self::KEY_DO_NOT_DISTURB => 591,
            Self::KEY_BRIGHTNESS_MIN => 592,
            Self::KEY_BRIGHTNESS_MAX => 593,
            Self::KEY_EPRIVACY_SCREEN_ON => 594,
            Self::KEY_EPRIVACY_SCREEN_OFF => 595,
            Self::KEY_ACTION_ON_SELECTION => 596,
            Self::KEY_CONTEXTUAL_INSERT => 597,
            Self::KEY_CONTEXTUAL_QUERY => 598,
            Self::KEY_KBDINPUTASSIST_PREV => 608,
            Self::KEY_KBDINPUTASSIST_NEXT => 609,
            Self::KEY_KBDINPUTASSIST_PREVGROUP => 610,
            Self::KEY_KBDINPUTASSIST_NEXTGROUP => 611,
            Self::KEY_KBDINPUTASSIST_ACCEPT => 612,
            Self::KEY_KBDINPUTASSIST_CANCEL => 613,
            Self::KEY_RIGHT_UP => 614,
            Self::KEY_RIGHT_DOWN => 615,
            Self::KEY_LEFT_UP => 616,
            Self::KEY_LEFT_DOWN => 617,
            Self::KEY_ROOT_MENU => 618,
            Self::KEY_MEDIA_TOP_MENU => 619,
            Self::KEY_NUMERIC_11 => 620,
            Self::KEY_NUMERIC_12 => 621,
            Self::KEY_AUDIO_DESC => 622,
            Self::KEY_3D_MODE => 623,
            Self::KEY_NEXT_FAVORITE => 624,
            Self::KEY_STOP_RECORD => 625,
            Self::KEY_PAUSE_RECORD => 626,
            Self::KEY_VOD => 627,
            Self::KEY_UNMUTE => 628,
            Self::KEY_FASTREVERSE => 629,
            Self::KEY_SLOWREVERSE => 630,
            Self::KEY_DATA => 631,
            Self::KEY_ONSCREEN_KEYBOARD => 632,
            Self::KEY_PRIVACY_SCREEN_TOGGLE => 633,
            Self::KEY_SELECTIVE_SCREENSHOT => 634,
            Self::KEY_NEXT_ELEMENT => 635,
            Self::KEY_PREVIOUS_ELEMENT => 636,
            Self::KEY_AUTOPILOT_ENGAGE_TOGGLE => 637,
            Self::KEY_MARK_WAYPOINT => 638,
            Self::KEY_SOS => 639,
            Self::KEY_NAV_CHART => 640,
            Self::KEY_FISHING_CHART => 641,
            Self::KEY_SINGLE_RANGE_RADAR => 642,
            Self::KEY_DUAL_RANGE_RADAR => 643,
            Self::KEY_RADAR_OVERLAY => 644,
            Self::KEY_TRADITIONAL_SONAR => 645,
            Self::KEY_CLEARVU_SONAR => 646,
            Self::KEY_SIDEVU_SONAR => 647,
            Self::KEY_NAV_INFO => 648,
            Self::KEY_BRIGHTNESS_MENU => 649,
            Self::KEY_MACRO1 => 656,
            Self::KEY_MACRO2 => 657,
            Self::KEY_MACRO3 => 658,
            Self::KEY_MACRO4 => 659,
            Self::KEY_MACRO5 => 660,
            Self::KEY_MACRO6 => 661,
            Self::KEY_MACRO7 => 662,
            Self::KEY_MACRO8 => 663,
            Self::KEY_MACRO9 => 664,
            Self::KEY_MACRO10 => 665,
            Self::KEY_MACRO11 => 666,
            Self::KEY_MACRO12 => 667,
            Self::KEY_MACRO13 => 668,
            Self::KEY_MACRO14 => 669,
            Self::KEY_MACRO15 => 670,
            Self::KEY_MACRO16 => 671,
            Self::KEY_MACRO17 => 672,
            Self::KEY_MACRO18 => 673,
            Self::KEY_MACRO19 => 674,
            Self::KEY_MACRO20 => 675,
            Self::KEY_MACRO21 => 676,
            Self::KEY_MACRO22 => 677,
            Self::KEY_MACRO23 => 678,
            Self::KEY_MACRO24 => 679,
            Self::KEY_MACRO25 => 680,
            Self::KEY_MACRO26 => 681,
            Self::KEY_MACRO27 => 682,
            Self::KEY_MACRO28 => 683,
            Self::KEY_MACRO29 => 684,
            Self::KEY_MACRO30 => 685,
            Self::KEY_MACRO_RECORD_START => 688,
            Self::KEY_MACRO_RECORD_STOP => 689,
            Self::KEY_MACRO_PRESET_CYCLE => 690,
            Self::KEY_MACRO_PRESET1 => 691,
            Self::KEY_MACRO_PRESET2 => 692,
            Self::KEY_MACRO_PRESET3 => 693,
            Self::KEY_KBD_LCD_MENU1 => 696,
            Self::KEY_KBD_LCD_MENU2 => 697,
            Self::KEY_KBD_LCD_MENU3 => 698,
            Self::KEY_KBD_LCD_MENU4 => 699,
            Self::KEY_KBD_LCD_MENU5 => 700,
            Self::KEY_PERFORMANCE => 701,
            Self::BTN_TRIGGER_HAPPY => 704,
            Self::BTN_TRIGGER_HAPPY2 => 705,
            Self::BTN_TRIGGER_HAPPY3 => 706,
            Self::BTN_TRIGGER_HAPPY4 => 707,
            Self::BTN_TRIGGER_HAPPY5 => 708,
            Self::BTN_TRIGGER_HAPPY6 => 709,
            Self::BTN_TRIGGER_HAPPY7 => 710,
            Self::BTN_TRIGGER_HAPPY8 => 711,
            Self::BTN_TRIGGER_HAPPY9 => 712,
            Self::BTN_TRIGGER_HAPPY10 => 713,
            Self::BTN_TRIGGER_HAPPY11 => 714,
            Self::BTN_TRIGGER_HAPPY12 => 715,
            Self::BTN_TRIGGER_HAPPY13 => 716,
            Self::BTN_TRIGGER_HAPPY14 => 717,
            Self::BTN_TRIGGER_HAPPY15 => 718,
            Self::BTN_TRIGGER_HAPPY16 => 719,
            Self::BTN_TRIGGER_HAPPY17 => 720,
            Self::BTN_TRIGGER_HAPPY18 => 721,
            Self::BTN_TRIGGER_HAPPY19 => 722,
            Self::BTN_TRIGGER_HAPPY20 => 723,
            Self::BTN_TRIGGER_HAPPY21 => 724,
            Self::BTN_TRIGGER_HAPPY22 => 725,
            Self::BTN_TRIGGER_HAPPY23 => 726,
            Self::BTN_TRIGGER_HAPPY24 => 727,
            Self::BTN_TRIGGER_HAPPY25 => 728,
            Self::BTN_TRIGGER_HAPPY26 => 729,
            Self::BTN_TRIGGER_HAPPY27 => 730,
            Self::BTN_TRIGGER_HAPPY28 => 731,
            Self::BTN_TRIGGER_HAPPY29 => 732,
            Self::BTN_TRIGGER_HAPPY30 => 733,
            Self::BTN_TRIGGER_HAPPY31 => 734,
            Self::BTN_TRIGGER_HAPPY32 => 735,
            Self::BTN_TRIGGER_HAPPY33 => 736,
            Self::BTN_TRIGGER_HAPPY34 => 737,
            Self::BTN_TRIGGER_HAPPY35 => 738,
            Self::BTN_TRIGGER_HAPPY36 => 739,
            Self::BTN_TRIGGER_HAPPY37 => 740,
            Self::BTN_TRIGGER_HAPPY38 => 741,
            Self::BTN_TRIGGER_HAPPY39 => 742,
            Self::BTN_TRIGGER_HAPPY40 => 743,
        }
    }

    pub fn from_raw(raw: u32) -> Option<Self> {
        static MAP: [Option<InputEventCode>; 744] = [
            None,
            Some(InputEventCode::KEY_ESC),
            Some(InputEventCode::KEY_1),
            Some(InputEventCode::KEY_2),
            Some(InputEventCode::KEY_3),
            Some(InputEventCode::KEY_4),
            Some(InputEventCode::KEY_5),
            Some(InputEventCode::KEY_6),
            Some(InputEventCode::KEY_7),
            Some(InputEventCode::KEY_8),
            Some(InputEventCode::KEY_9),
            Some(InputEventCode::KEY_0),
            Some(InputEventCode::KEY_MINUS),
            Some(InputEventCode::KEY_EQUAL),
            Some(InputEventCode::KEY_BACKSPACE),
            Some(InputEventCode::KEY_TAB),
            Some(InputEventCode::KEY_Q),
            Some(InputEventCode::KEY_W),
            Some(InputEventCode::KEY_E),
            Some(InputEventCode::KEY_R),
            Some(InputEventCode::KEY_T),
            Some(InputEventCode::KEY_Y),
            Some(InputEventCode::KEY_U),
            Some(InputEventCode::KEY_I),
            Some(InputEventCode::KEY_O),
            Some(InputEventCode::KEY_P),
            Some(InputEventCode::KEY_LEFTBRACE),
            Some(InputEventCode::KEY_RIGHTBRACE),
            Some(InputEventCode::KEY_ENTER),
            Some(InputEventCode::KEY_LEFTCTRL),
            Some(InputEventCode::KEY_A),
            Some(InputEventCode::KEY_S),
            Some(InputEventCode::KEY_D),
            Some(InputEventCode::KEY_F),
            Some(InputEventCode::KEY_G),
            Some(InputEventCode::KEY_H),
            Some(InputEventCode::KEY_J),
            Some(InputEventCode::KEY_K),
            Some(InputEventCode::KEY_L),
            Some(InputEventCode::KEY_SEMICOLON),
            Some(InputEventCode::KEY_APOSTROPHE),
            Some(InputEventCode::KEY_GRAVE),
            Some(InputEventCode::KEY_LEFTSHIFT),
            Some(InputEventCode::KEY_BACKSLASH),
            Some(InputEventCode::KEY_Z),
            Some(InputEventCode::KEY_X),
            Some(InputEventCode::KEY_C),
            Some(InputEventCode::KEY_V),
            Some(InputEventCode::KEY_B),
            Some(InputEventCode::KEY_N),
            Some(InputEventCode::KEY_M),
            Some(InputEventCode::KEY_COMMA),
            Some(InputEventCode::KEY_DOT),
            Some(InputEventCode::KEY_SLASH),
            Some(InputEventCode::KEY_RIGHTSHIFT),
            Some(InputEventCode::KEY_KPASTERISK),
            Some(InputEventCode::KEY_LEFTALT),
            Some(InputEventCode::KEY_SPACE),
            Some(InputEventCode::KEY_CAPSLOCK),
            Some(InputEventCode::KEY_F1),
            Some(InputEventCode::KEY_F2),
            Some(InputEventCode::KEY_F3),
            Some(InputEventCode::KEY_F4),
            Some(InputEventCode::KEY_F5),
            Some(InputEventCode::KEY_F6),
            Some(InputEventCode::KEY_F7),
            Some(InputEventCode::KEY_F8),
            Some(InputEventCode::KEY_F9),
            Some(InputEventCode::KEY_F10),
            Some(InputEventCode::KEY_NUMLOCK),
            Some(InputEventCode::KEY_SCROLLLOCK),
            Some(InputEventCode::KEY_KP7),
            Some(InputEventCode::KEY_KP8),
            Some(InputEventCode::KEY_KP9),
            Some(InputEventCode::KEY_KPMINUS),
            Some(InputEventCode::KEY_KP4),
            Some(InputEventCode::KEY_KP5),
            Some(InputEventCode::KEY_KP6),
            Some(InputEventCode::KEY_KPPLUS),
            Some(InputEventCode::KEY_KP1),
            Some(InputEventCode::KEY_KP2),
            Some(InputEventCode::KEY_KP3),
            Some(InputEventCode::KEY_KP0),
            Some(InputEventCode::KEY_KPDOT),
            None,
            Some(InputEventCode::KEY_ZENKAKUHANKAKU),
            Some(InputEventCode::KEY_102ND),
            Some(InputEventCode::KEY_F11),
            Some(InputEventCode::KEY_F12),
            Some(InputEventCode::KEY_RO),
            Some(InputEventCode::KEY_KATAKANA),
            Some(InputEventCode::KEY_HIRAGANA),
            Some(InputEventCode::KEY_HENKAN),
            Some(InputEventCode::KEY_KATAKANAHIRAGANA),
            Some(InputEventCode::KEY_MUHENKAN),
            Some(InputEventCode::KEY_KPJPCOMMA),
            Some(InputEventCode::KEY_KPENTER),
            Some(InputEventCode::KEY_RIGHTCTRL),
            Some(InputEventCode::KEY_KPSLASH),
            Some(InputEventCode::KEY_SYSRQ),
            Some(InputEventCode::KEY_RIGHTALT),
            Some(InputEventCode::KEY_LINEFEED),
            Some(InputEventCode::KEY_HOME),
            Some(InputEventCode::KEY_UP),
            Some(InputEventCode::KEY_PAGEUP),
            Some(InputEventCode::KEY_LEFT),
            Some(InputEventCode::KEY_RIGHT),
            Some(InputEventCode::KEY_END),
            Some(InputEventCode::KEY_DOWN),
            Some(InputEventCode::KEY_PAGEDOWN),
            Some(InputEventCode::KEY_INSERT),
            Some(InputEventCode::KEY_DELETE),
            Some(InputEventCode::KEY_MACRO),
            Some(InputEventCode::KEY_MUTE),
            Some(InputEventCode::KEY_VOLUMEDOWN),
            Some(InputEventCode::KEY_VOLUMEUP),
            Some(InputEventCode::KEY_POWER),
            Some(InputEventCode::KEY_KPEQUAL),
            Some(InputEventCode::KEY_KPPLUSMINUS),
            Some(InputEventCode::KEY_PAUSE),
            Some(InputEventCode::KEY_SCALE),
            Some(InputEventCode::KEY_KPCOMMA),
            Some(InputEventCode::KEY_HANGEUL),
            Some(InputEventCode::KEY_HANJA),
            Some(InputEventCode::KEY_YEN),
            Some(InputEventCode::KEY_LEFTMETA),
            Some(InputEventCode::KEY_RIGHTMETA),
            Some(InputEventCode::KEY_COMPOSE),
            Some(InputEventCode::KEY_STOP),
            Some(InputEventCode::KEY_AGAIN),
            Some(InputEventCode::KEY_PROPS),
            Some(InputEventCode::KEY_UNDO),
            Some(InputEventCode::KEY_FRONT),
            Some(InputEventCode::KEY_COPY),
            Some(InputEventCode::KEY_OPEN),
            Some(InputEventCode::KEY_PASTE),
            Some(InputEventCode::KEY_FIND),
            Some(InputEventCode::KEY_CUT),
            Some(InputEventCode::KEY_HELP),
            Some(InputEventCode::KEY_MENU),
            Some(InputEventCode::KEY_CALC),
            Some(InputEventCode::KEY_SETUP),
            Some(InputEventCode::KEY_SLEEP),
            Some(InputEventCode::KEY_WAKEUP),
            Some(InputEventCode::KEY_FILE),
            Some(InputEventCode::KEY_SENDFILE),
            Some(InputEventCode::KEY_DELETEFILE),
            Some(InputEventCode::KEY_XFER),
            Some(InputEventCode::KEY_PROG1),
            Some(InputEventCode::KEY_PROG2),
            Some(InputEventCode::KEY_WWW),
            Some(InputEventCode::KEY_MSDOS),
            Some(InputEventCode::KEY_COFFEE),
            Some(InputEventCode::KEY_ROTATE_DISPLAY),
            Some(InputEventCode::KEY_CYCLEWINDOWS),
            Some(InputEventCode::KEY_MAIL),
            Some(InputEventCode::KEY_BOOKMARKS),
            Some(InputEventCode::KEY_COMPUTER),
            Some(InputEventCode::KEY_BACK),
            Some(InputEventCode::KEY_FORWARD),
            Some(InputEventCode::KEY_CLOSECD),
            Some(InputEventCode::KEY_EJECTCD),
            Some(InputEventCode::KEY_EJECTCLOSECD),
            Some(InputEventCode::KEY_NEXTSONG),
            Some(InputEventCode::KEY_PLAYPAUSE),
            Some(InputEventCode::KEY_PREVIOUSSONG),
            Some(InputEventCode::KEY_STOPCD),
            Some(InputEventCode::KEY_RECORD),
            Some(InputEventCode::KEY_REWIND),
            Some(InputEventCode::KEY_PHONE),
            Some(InputEventCode::KEY_ISO),
            Some(InputEventCode::KEY_CONFIG),
            Some(InputEventCode::KEY_HOMEPAGE),
            Some(InputEventCode::KEY_REFRESH),
            Some(InputEventCode::KEY_EXIT),
            Some(InputEventCode::KEY_MOVE),
            Some(InputEventCode::KEY_EDIT),
            Some(InputEventCode::KEY_SCROLLUP),
            Some(InputEventCode::KEY_SCROLLDOWN),
            Some(InputEventCode::KEY_KPLEFTPAREN),
            Some(InputEventCode::KEY_KPRIGHTPAREN),
            Some(InputEventCode::KEY_NEW),
            Some(InputEventCode::KEY_REDO),
            Some(InputEventCode::KEY_F13),
            Some(InputEventCode::KEY_F14),
            Some(InputEventCode::KEY_F15),
            Some(InputEventCode::KEY_F16),
            Some(InputEventCode::KEY_F17),
            Some(InputEventCode::KEY_F18),
            Some(InputEventCode::KEY_F19),
            Some(InputEventCode::KEY_F20),
            Some(InputEventCode::KEY_F21),
            Some(InputEventCode::KEY_F22),
            Some(InputEventCode::KEY_F23),
            Some(InputEventCode::KEY_F24),
            None,
            None,
            None,
            None,
            None,
            Some(InputEventCode::KEY_PLAYCD),
            Some(InputEventCode::KEY_PAUSECD),
            Some(InputEventCode::KEY_PROG3),
            Some(InputEventCode::KEY_PROG4),
            Some(InputEventCode::KEY_ALL_APPLICATIONS),
            Some(InputEventCode::KEY_SUSPEND),
            Some(InputEventCode::KEY_CLOSE),
            Some(InputEventCode::KEY_PLAY),
            Some(InputEventCode::KEY_FASTFORWARD),
            Some(InputEventCode::KEY_BASSBOOST),
            Some(InputEventCode::KEY_PRINT),
            Some(InputEventCode::KEY_HP),
            Some(InputEventCode::KEY_CAMERA),
            Some(InputEventCode::KEY_SOUND),
            Some(InputEventCode::KEY_QUESTION),
            Some(InputEventCode::KEY_EMAIL),
            Some(InputEventCode::KEY_CHAT),
            Some(InputEventCode::KEY_SEARCH),
            Some(InputEventCode::KEY_CONNECT),
            Some(InputEventCode::KEY_FINANCE),
            Some(InputEventCode::KEY_SPORT),
            Some(InputEventCode::KEY_SHOP),
            Some(InputEventCode::KEY_ALTERASE),
            Some(InputEventCode::KEY_CANCEL),
            Some(InputEventCode::KEY_BRIGHTNESSDOWN),
            Some(InputEventCode::KEY_BRIGHTNESSUP),
            Some(InputEventCode::KEY_MEDIA),
            Some(InputEventCode::KEY_SWITCHVIDEOMODE),
            Some(InputEventCode::KEY_KBDILLUMTOGGLE),
            Some(InputEventCode::KEY_KBDILLUMDOWN),
            Some(InputEventCode::KEY_KBDILLUMUP),
            Some(InputEventCode::KEY_SEND),
            Some(InputEventCode::KEY_REPLY),
            Some(InputEventCode::KEY_FORWARDMAIL),
            Some(InputEventCode::KEY_SAVE),
            Some(InputEventCode::KEY_DOCUMENTS),
            Some(InputEventCode::KEY_BATTERY),
            Some(InputEventCode::KEY_BLUETOOTH),
            Some(InputEventCode::KEY_WLAN),
            Some(InputEventCode::KEY_UWB),
            Some(InputEventCode::KEY_UNKNOWN),
            Some(InputEventCode::KEY_VIDEO_NEXT),
            Some(InputEventCode::KEY_VIDEO_PREV),
            Some(InputEventCode::KEY_BRIGHTNESS_CYCLE),
            Some(InputEventCode::KEY_BRIGHTNESS_AUTO),
            Some(InputEventCode::KEY_DISPLAY_OFF),
            Some(InputEventCode::KEY_WWAN),
            Some(InputEventCode::KEY_RFKILL),
            Some(InputEventCode::KEY_MICMUTE),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(InputEventCode::BTN_MISC),
            Some(InputEventCode::BTN_1),
            Some(InputEventCode::BTN_2),
            Some(InputEventCode::BTN_3),
            Some(InputEventCode::BTN_4),
            Some(InputEventCode::BTN_5),
            Some(InputEventCode::BTN_6),
            Some(InputEventCode::BTN_7),
            Some(InputEventCode::BTN_8),
            Some(InputEventCode::BTN_9),
            None,
            None,
            None,
            None,
            None,
            None,
            Some(InputEventCode::BTN_MOUSE),
            Some(InputEventCode::BTN_RIGHT),
            Some(InputEventCode::BTN_MIDDLE),
            Some(InputEventCode::BTN_SIDE),
            Some(InputEventCode::BTN_EXTRA),
            Some(InputEventCode::BTN_FORWARD),
            Some(InputEventCode::BTN_BACK),
            Some(InputEventCode::BTN_TASK),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(InputEventCode::BTN_JOYSTICK),
            Some(InputEventCode::BTN_THUMB),
            Some(InputEventCode::BTN_THUMB2),
            Some(InputEventCode::BTN_TOP),
            Some(InputEventCode::BTN_TOP2),
            Some(InputEventCode::BTN_PINKIE),
            Some(InputEventCode::BTN_BASE),
            Some(InputEventCode::BTN_BASE2),
            Some(InputEventCode::BTN_BASE3),
            Some(InputEventCode::BTN_BASE4),
            Some(InputEventCode::BTN_BASE5),
            Some(InputEventCode::BTN_BASE6),
            None,
            None,
            None,
            Some(InputEventCode::BTN_DEAD),
            Some(InputEventCode::BTN_GAMEPAD),
            Some(InputEventCode::BTN_EAST),
            Some(InputEventCode::BTN_C),
            Some(InputEventCode::BTN_NORTH),
            Some(InputEventCode::BTN_WEST),
            Some(InputEventCode::BTN_Z),
            Some(InputEventCode::BTN_TL),
            Some(InputEventCode::BTN_TR),
            Some(InputEventCode::BTN_TL2),
            Some(InputEventCode::BTN_TR2),
            Some(InputEventCode::BTN_SELECT),
            Some(InputEventCode::BTN_START),
            Some(InputEventCode::BTN_MODE),
            Some(InputEventCode::BTN_THUMBL),
            Some(InputEventCode::BTN_THUMBR),
            None,
            Some(InputEventCode::BTN_DIGI),
            Some(InputEventCode::BTN_TOOL_RUBBER),
            Some(InputEventCode::BTN_TOOL_BRUSH),
            Some(InputEventCode::BTN_TOOL_PENCIL),
            Some(InputEventCode::BTN_TOOL_AIRBRUSH),
            Some(InputEventCode::BTN_TOOL_FINGER),
            Some(InputEventCode::BTN_TOOL_MOUSE),
            Some(InputEventCode::BTN_TOOL_LENS),
            Some(InputEventCode::BTN_TOOL_QUINTTAP),
            Some(InputEventCode::BTN_STYLUS3),
            Some(InputEventCode::BTN_TOUCH),
            Some(InputEventCode::BTN_STYLUS),
            Some(InputEventCode::BTN_STYLUS2),
            Some(InputEventCode::BTN_TOOL_DOUBLETAP),
            Some(InputEventCode::BTN_TOOL_TRIPLETAP),
            Some(InputEventCode::BTN_TOOL_QUADTAP),
            Some(InputEventCode::BTN_WHEEL),
            Some(InputEventCode::BTN_GEAR_UP),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(InputEventCode::KEY_OK),
            Some(InputEventCode::KEY_SELECT),
            Some(InputEventCode::KEY_GOTO),
            Some(InputEventCode::KEY_CLEAR),
            Some(InputEventCode::KEY_POWER2),
            Some(InputEventCode::KEY_OPTION),
            Some(InputEventCode::KEY_INFO),
            Some(InputEventCode::KEY_TIME),
            Some(InputEventCode::KEY_VENDOR),
            Some(InputEventCode::KEY_ARCHIVE),
            Some(InputEventCode::KEY_PROGRAM),
            Some(InputEventCode::KEY_CHANNEL),
            Some(InputEventCode::KEY_FAVORITES),
            Some(InputEventCode::KEY_EPG),
            Some(InputEventCode::KEY_PVR),
            Some(InputEventCode::KEY_MHP),
            Some(InputEventCode::KEY_LANGUAGE),
            Some(InputEventCode::KEY_TITLE),
            Some(InputEventCode::KEY_SUBTITLE),
            Some(InputEventCode::KEY_ANGLE),
            Some(InputEventCode::KEY_FULL_SCREEN),
            Some(InputEventCode::KEY_MODE),
            Some(InputEventCode::KEY_KEYBOARD),
            Some(InputEventCode::KEY_ASPECT_RATIO),
            Some(InputEventCode::KEY_PC),
            Some(InputEventCode::KEY_TV),
            Some(InputEventCode::KEY_TV2),
            Some(InputEventCode::KEY_VCR),
            Some(InputEventCode::KEY_VCR2),
            Some(InputEventCode::KEY_SAT),
            Some(InputEventCode::KEY_SAT2),
            Some(InputEventCode::KEY_CD),
            Some(InputEventCode::KEY_TAPE),
            Some(InputEventCode::KEY_RADIO),
            Some(InputEventCode::KEY_TUNER),
            Some(InputEventCode::KEY_PLAYER),
            Some(InputEventCode::KEY_TEXT),
            Some(InputEventCode::KEY_DVD),
            Some(InputEventCode::KEY_AUX),
            Some(InputEventCode::KEY_MP3),
            Some(InputEventCode::KEY_AUDIO),
            Some(InputEventCode::KEY_VIDEO),
            Some(InputEventCode::KEY_DIRECTORY),
            Some(InputEventCode::KEY_LIST),
            Some(InputEventCode::KEY_MEMO),
            Some(InputEventCode::KEY_CALENDAR),
            Some(InputEventCode::KEY_RED),
            Some(InputEventCode::KEY_GREEN),
            Some(InputEventCode::KEY_YELLOW),
            Some(InputEventCode::KEY_BLUE),
            Some(InputEventCode::KEY_CHANNELUP),
            Some(InputEventCode::KEY_CHANNELDOWN),
            Some(InputEventCode::KEY_FIRST),
            Some(InputEventCode::KEY_LAST),
            Some(InputEventCode::KEY_AB),
            Some(InputEventCode::KEY_NEXT),
            Some(InputEventCode::KEY_RESTART),
            Some(InputEventCode::KEY_SLOW),
            Some(InputEventCode::KEY_SHUFFLE),
            Some(InputEventCode::KEY_BREAK),
            Some(InputEventCode::KEY_PREVIOUS),
            Some(InputEventCode::KEY_DIGITS),
            Some(InputEventCode::KEY_TEEN),
            Some(InputEventCode::KEY_TWEN),
            Some(InputEventCode::KEY_VIDEOPHONE),
            Some(InputEventCode::KEY_GAMES),
            Some(InputEventCode::KEY_ZOOMIN),
            Some(InputEventCode::KEY_ZOOMOUT),
            Some(InputEventCode::KEY_ZOOMRESET),
            Some(InputEventCode::KEY_WORDPROCESSOR),
            Some(InputEventCode::KEY_EDITOR),
            Some(InputEventCode::KEY_SPREADSHEET),
            Some(InputEventCode::KEY_GRAPHICSEDITOR),
            Some(InputEventCode::KEY_PRESENTATION),
            Some(InputEventCode::KEY_DATABASE),
            Some(InputEventCode::KEY_NEWS),
            Some(InputEventCode::KEY_VOICEMAIL),
            Some(InputEventCode::KEY_ADDRESSBOOK),
            Some(InputEventCode::KEY_MESSENGER),
            Some(InputEventCode::KEY_DISPLAYTOGGLE),
            Some(InputEventCode::KEY_SPELLCHECK),
            Some(InputEventCode::KEY_LOGOFF),
            Some(InputEventCode::KEY_DOLLAR),
            Some(InputEventCode::KEY_EURO),
            Some(InputEventCode::KEY_FRAMEBACK),
            Some(InputEventCode::KEY_FRAMEFORWARD),
            Some(InputEventCode::KEY_CONTEXT_MENU),
            Some(InputEventCode::KEY_MEDIA_REPEAT),
            Some(InputEventCode::KEY_10CHANNELSUP),
            Some(InputEventCode::KEY_10CHANNELSDOWN),
            Some(InputEventCode::KEY_IMAGES),
            None,
            Some(InputEventCode::KEY_NOTIFICATION_CENTER),
            Some(InputEventCode::KEY_PICKUP_PHONE),
            Some(InputEventCode::KEY_HANGUP_PHONE),
            Some(InputEventCode::KEY_LINK_PHONE),
            Some(InputEventCode::KEY_DEL_EOL),
            Some(InputEventCode::KEY_DEL_EOS),
            Some(InputEventCode::KEY_INS_LINE),
            Some(InputEventCode::KEY_DEL_LINE),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(InputEventCode::KEY_FN),
            Some(InputEventCode::KEY_FN_ESC),
            Some(InputEventCode::KEY_FN_F1),
            Some(InputEventCode::KEY_FN_F2),
            Some(InputEventCode::KEY_FN_F3),
            Some(InputEventCode::KEY_FN_F4),
            Some(InputEventCode::KEY_FN_F5),
            Some(InputEventCode::KEY_FN_F6),
            Some(InputEventCode::KEY_FN_F7),
            Some(InputEventCode::KEY_FN_F8),
            Some(InputEventCode::KEY_FN_F9),
            Some(InputEventCode::KEY_FN_F10),
            Some(InputEventCode::KEY_FN_F11),
            Some(InputEventCode::KEY_FN_F12),
            Some(InputEventCode::KEY_FN_1),
            Some(InputEventCode::KEY_FN_2),
            Some(InputEventCode::KEY_FN_D),
            Some(InputEventCode::KEY_FN_E),
            Some(InputEventCode::KEY_FN_F),
            Some(InputEventCode::KEY_FN_S),
            Some(InputEventCode::KEY_FN_B),
            Some(InputEventCode::KEY_FN_RIGHT_SHIFT),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(InputEventCode::KEY_BRL_DOT1),
            Some(InputEventCode::KEY_BRL_DOT2),
            Some(InputEventCode::KEY_BRL_DOT3),
            Some(InputEventCode::KEY_BRL_DOT4),
            Some(InputEventCode::KEY_BRL_DOT5),
            Some(InputEventCode::KEY_BRL_DOT6),
            Some(InputEventCode::KEY_BRL_DOT7),
            Some(InputEventCode::KEY_BRL_DOT8),
            Some(InputEventCode::KEY_BRL_DOT9),
            Some(InputEventCode::KEY_BRL_DOT10),
            None,
            None,
            None,
            None,
            None,
            Some(InputEventCode::KEY_NUMERIC_0),
            Some(InputEventCode::KEY_NUMERIC_1),
            Some(InputEventCode::KEY_NUMERIC_2),
            Some(InputEventCode::KEY_NUMERIC_3),
            Some(InputEventCode::KEY_NUMERIC_4),
            Some(InputEventCode::KEY_NUMERIC_5),
            Some(InputEventCode::KEY_NUMERIC_6),
            Some(InputEventCode::KEY_NUMERIC_7),
            Some(InputEventCode::KEY_NUMERIC_8),
            Some(InputEventCode::KEY_NUMERIC_9),
            Some(InputEventCode::KEY_NUMERIC_STAR),
            Some(InputEventCode::KEY_NUMERIC_POUND),
            Some(InputEventCode::KEY_NUMERIC_A),
            Some(InputEventCode::KEY_NUMERIC_B),
            Some(InputEventCode::KEY_NUMERIC_C),
            Some(InputEventCode::KEY_NUMERIC_D),
            Some(InputEventCode::KEY_CAMERA_FOCUS),
            Some(InputEventCode::KEY_WPS_BUTTON),
            Some(InputEventCode::KEY_TOUCHPAD_TOGGLE),
            Some(InputEventCode::KEY_TOUCHPAD_ON),
            Some(InputEventCode::KEY_TOUCHPAD_OFF),
            Some(InputEventCode::KEY_CAMERA_ZOOMIN),
            Some(InputEventCode::KEY_CAMERA_ZOOMOUT),
            Some(InputEventCode::KEY_CAMERA_UP),
            Some(InputEventCode::KEY_CAMERA_DOWN),
            Some(InputEventCode::KEY_CAMERA_LEFT),
            Some(InputEventCode::KEY_CAMERA_RIGHT),
            Some(InputEventCode::KEY_ATTENDANT_ON),
            Some(InputEventCode::KEY_ATTENDANT_OFF),
            Some(InputEventCode::KEY_ATTENDANT_TOGGLE),
            Some(InputEventCode::KEY_LIGHTS_TOGGLE),
            None,
            Some(InputEventCode::BTN_DPAD_UP),
            Some(InputEventCode::BTN_DPAD_DOWN),
            Some(InputEventCode::BTN_DPAD_LEFT),
            Some(InputEventCode::BTN_DPAD_RIGHT),
            Some(InputEventCode::BTN_GRIPL),
            Some(InputEventCode::BTN_GRIPR),
            Some(InputEventCode::BTN_GRIPL2),
            Some(InputEventCode::BTN_GRIPR2),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(InputEventCode::KEY_ALS_TOGGLE),
            Some(InputEventCode::KEY_ROTATE_LOCK_TOGGLE),
            Some(InputEventCode::KEY_REFRESH_RATE_TOGGLE),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(InputEventCode::KEY_BUTTONCONFIG),
            Some(InputEventCode::KEY_TASKMANAGER),
            Some(InputEventCode::KEY_JOURNAL),
            Some(InputEventCode::KEY_CONTROLPANEL),
            Some(InputEventCode::KEY_APPSELECT),
            Some(InputEventCode::KEY_SCREENSAVER),
            Some(InputEventCode::KEY_VOICECOMMAND),
            Some(InputEventCode::KEY_ASSISTANT),
            Some(InputEventCode::KEY_KBD_LAYOUT_NEXT),
            Some(InputEventCode::KEY_EMOJI_PICKER),
            Some(InputEventCode::KEY_DICTATE),
            Some(InputEventCode::KEY_CAMERA_ACCESS_ENABLE),
            Some(InputEventCode::KEY_CAMERA_ACCESS_DISABLE),
            Some(InputEventCode::KEY_CAMERA_ACCESS_TOGGLE),
            Some(InputEventCode::KEY_ACCESSIBILITY),
            Some(InputEventCode::KEY_DO_NOT_DISTURB),
            Some(InputEventCode::KEY_BRIGHTNESS_MIN),
            Some(InputEventCode::KEY_BRIGHTNESS_MAX),
            Some(InputEventCode::KEY_EPRIVACY_SCREEN_ON),
            Some(InputEventCode::KEY_EPRIVACY_SCREEN_OFF),
            Some(InputEventCode::KEY_ACTION_ON_SELECTION),
            Some(InputEventCode::KEY_CONTEXTUAL_INSERT),
            Some(InputEventCode::KEY_CONTEXTUAL_QUERY),
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            Some(InputEventCode::KEY_KBDINPUTASSIST_PREV),
            Some(InputEventCode::KEY_KBDINPUTASSIST_NEXT),
            Some(InputEventCode::KEY_KBDINPUTASSIST_PREVGROUP),
            Some(InputEventCode::KEY_KBDINPUTASSIST_NEXTGROUP),
            Some(InputEventCode::KEY_KBDINPUTASSIST_ACCEPT),
            Some(InputEventCode::KEY_KBDINPUTASSIST_CANCEL),
            Some(InputEventCode::KEY_RIGHT_UP),
            Some(InputEventCode::KEY_RIGHT_DOWN),
            Some(InputEventCode::KEY_LEFT_UP),
            Some(InputEventCode::KEY_LEFT_DOWN),
            Some(InputEventCode::KEY_ROOT_MENU),
            Some(InputEventCode::KEY_MEDIA_TOP_MENU),
            Some(InputEventCode::KEY_NUMERIC_11),
            Some(InputEventCode::KEY_NUMERIC_12),
            Some(InputEventCode::KEY_AUDIO_DESC),
            Some(InputEventCode::KEY_3D_MODE),
            Some(InputEventCode::KEY_NEXT_FAVORITE),
            Some(InputEventCode::KEY_STOP_RECORD),
            Some(InputEventCode::KEY_PAUSE_RECORD),
            Some(InputEventCode::KEY_VOD),
            Some(InputEventCode::KEY_UNMUTE),
            Some(InputEventCode::KEY_FASTREVERSE),
            Some(InputEventCode::KEY_SLOWREVERSE),
            Some(InputEventCode::KEY_DATA),
            Some(InputEventCode::KEY_ONSCREEN_KEYBOARD),
            Some(InputEventCode::KEY_PRIVACY_SCREEN_TOGGLE),
            Some(InputEventCode::KEY_SELECTIVE_SCREENSHOT),
            Some(InputEventCode::KEY_NEXT_ELEMENT),
            Some(InputEventCode::KEY_PREVIOUS_ELEMENT),
            Some(InputEventCode::KEY_AUTOPILOT_ENGAGE_TOGGLE),
            Some(InputEventCode::KEY_MARK_WAYPOINT),
            Some(InputEventCode::KEY_SOS),
            Some(InputEventCode::KEY_NAV_CHART),
            Some(InputEventCode::KEY_FISHING_CHART),
            Some(InputEventCode::KEY_SINGLE_RANGE_RADAR),
            Some(InputEventCode::KEY_DUAL_RANGE_RADAR),
            Some(InputEventCode::KEY_RADAR_OVERLAY),
            Some(InputEventCode::KEY_TRADITIONAL_SONAR),
            Some(InputEventCode::KEY_CLEARVU_SONAR),
            Some(InputEventCode::KEY_SIDEVU_SONAR),
            Some(InputEventCode::KEY_NAV_INFO),
            Some(InputEventCode::KEY_BRIGHTNESS_MENU),
            None,
            None,
            None,
            None,
            None,
            None,
            Some(InputEventCode::KEY_MACRO1),
            Some(InputEventCode::KEY_MACRO2),
            Some(InputEventCode::KEY_MACRO3),
            Some(InputEventCode::KEY_MACRO4),
            Some(InputEventCode::KEY_MACRO5),
            Some(InputEventCode::KEY_MACRO6),
            Some(InputEventCode::KEY_MACRO7),
            Some(InputEventCode::KEY_MACRO8),
            Some(InputEventCode::KEY_MACRO9),
            Some(InputEventCode::KEY_MACRO10),
            Some(InputEventCode::KEY_MACRO11),
            Some(InputEventCode::KEY_MACRO12),
            Some(InputEventCode::KEY_MACRO13),
            Some(InputEventCode::KEY_MACRO14),
            Some(InputEventCode::KEY_MACRO15),
            Some(InputEventCode::KEY_MACRO16),
            Some(InputEventCode::KEY_MACRO17),
            Some(InputEventCode::KEY_MACRO18),
            Some(InputEventCode::KEY_MACRO19),
            Some(InputEventCode::KEY_MACRO20),
            Some(InputEventCode::KEY_MACRO21),
            Some(InputEventCode::KEY_MACRO22),
            Some(InputEventCode::KEY_MACRO23),
            Some(InputEventCode::KEY_MACRO24),
            Some(InputEventCode::KEY_MACRO25),
            Some(InputEventCode::KEY_MACRO26),
            Some(InputEventCode::KEY_MACRO27),
            Some(InputEventCode::KEY_MACRO28),
            Some(InputEventCode::KEY_MACRO29),
            Some(InputEventCode::KEY_MACRO30),
            None,
            None,
            Some(InputEventCode::KEY_MACRO_RECORD_START),
            Some(InputEventCode::KEY_MACRO_RECORD_STOP),
            Some(InputEventCode::KEY_MACRO_PRESET_CYCLE),
            Some(InputEventCode::KEY_MACRO_PRESET1),
            Some(InputEventCode::KEY_MACRO_PRESET2),
            Some(InputEventCode::KEY_MACRO_PRESET3),
            None,
            None,
            Some(InputEventCode::KEY_KBD_LCD_MENU1),
            Some(InputEventCode::KEY_KBD_LCD_MENU2),
            Some(InputEventCode::KEY_KBD_LCD_MENU3),
            Some(InputEventCode::KEY_KBD_LCD_MENU4),
            Some(InputEventCode::KEY_KBD_LCD_MENU5),
            Some(InputEventCode::KEY_PERFORMANCE),
            None,
            None,
            Some(InputEventCode::BTN_TRIGGER_HAPPY),
            Some(InputEventCode::BTN_TRIGGER_HAPPY2),
            Some(InputEventCode::BTN_TRIGGER_HAPPY3),
            Some(InputEventCode::BTN_TRIGGER_HAPPY4),
            Some(InputEventCode::BTN_TRIGGER_HAPPY5),
            Some(InputEventCode::BTN_TRIGGER_HAPPY6),
            Some(InputEventCode::BTN_TRIGGER_HAPPY7),
            Some(InputEventCode::BTN_TRIGGER_HAPPY8),
            Some(InputEventCode::BTN_TRIGGER_HAPPY9),
            Some(InputEventCode::BTN_TRIGGER_HAPPY10),
            Some(InputEventCode::BTN_TRIGGER_HAPPY11),
            Some(InputEventCode::BTN_TRIGGER_HAPPY12),
            Some(InputEventCode::BTN_TRIGGER_HAPPY13),
            Some(InputEventCode::BTN_TRIGGER_HAPPY14),
            Some(InputEventCode::BTN_TRIGGER_HAPPY15),
            Some(InputEventCode::BTN_TRIGGER_HAPPY16),
            Some(InputEventCode::BTN_TRIGGER_HAPPY17),
            Some(InputEventCode::BTN_TRIGGER_HAPPY18),
            Some(InputEventCode::BTN_TRIGGER_HAPPY19),
            Some(InputEventCode::BTN_TRIGGER_HAPPY20),
            Some(InputEventCode::BTN_TRIGGER_HAPPY21),
            Some(InputEventCode::BTN_TRIGGER_HAPPY22),
            Some(InputEventCode::BTN_TRIGGER_HAPPY23),
            Some(InputEventCode::BTN_TRIGGER_HAPPY24),
            Some(InputEventCode::BTN_TRIGGER_HAPPY25),
            Some(InputEventCode::BTN_TRIGGER_HAPPY26),
            Some(InputEventCode::BTN_TRIGGER_HAPPY27),
            Some(InputEventCode::BTN_TRIGGER_HAPPY28),
            Some(InputEventCode::BTN_TRIGGER_HAPPY29),
            Some(InputEventCode::BTN_TRIGGER_HAPPY30),
            Some(InputEventCode::BTN_TRIGGER_HAPPY31),
            Some(InputEventCode::BTN_TRIGGER_HAPPY32),
            Some(InputEventCode::BTN_TRIGGER_HAPPY33),
            Some(InputEventCode::BTN_TRIGGER_HAPPY34),
            Some(InputEventCode::BTN_TRIGGER_HAPPY35),
            Some(InputEventCode::BTN_TRIGGER_HAPPY36),
            Some(InputEventCode::BTN_TRIGGER_HAPPY37),
            Some(InputEventCode::BTN_TRIGGER_HAPPY38),
            Some(InputEventCode::BTN_TRIGGER_HAPPY39),
            Some(InputEventCode::BTN_TRIGGER_HAPPY40),
        ];
        MAP.get(raw as usize).copied().flatten()
    }
}

impl crate::utils::static_text::StaticText for InputEventCode {
    fn text(&self) -> &'static str {
        match self {
            Self::KEY_ESC => "KEY_ESC",
            Self::KEY_1 => "KEY_1",
            Self::KEY_2 => "KEY_2",
            Self::KEY_3 => "KEY_3",
            Self::KEY_4 => "KEY_4",
            Self::KEY_5 => "KEY_5",
            Self::KEY_6 => "KEY_6",
            Self::KEY_7 => "KEY_7",
            Self::KEY_8 => "KEY_8",
            Self::KEY_9 => "KEY_9",
            Self::KEY_0 => "KEY_0",
            Self::KEY_MINUS => "KEY_MINUS",
            Self::KEY_EQUAL => "KEY_EQUAL",
            Self::KEY_BACKSPACE => "KEY_BACKSPACE",
            Self::KEY_TAB => "KEY_TAB",
            Self::KEY_Q => "KEY_Q",
            Self::KEY_W => "KEY_W",
            Self::KEY_E => "KEY_E",
            Self::KEY_R => "KEY_R",
            Self::KEY_T => "KEY_T",
            Self::KEY_Y => "KEY_Y",
            Self::KEY_U => "KEY_U",
            Self::KEY_I => "KEY_I",
            Self::KEY_O => "KEY_O",
            Self::KEY_P => "KEY_P",
            Self::KEY_LEFTBRACE => "KEY_LEFTBRACE",
            Self::KEY_RIGHTBRACE => "KEY_RIGHTBRACE",
            Self::KEY_ENTER => "KEY_ENTER",
            Self::KEY_LEFTCTRL => "KEY_LEFTCTRL",
            Self::KEY_A => "KEY_A",
            Self::KEY_S => "KEY_S",
            Self::KEY_D => "KEY_D",
            Self::KEY_F => "KEY_F",
            Self::KEY_G => "KEY_G",
            Self::KEY_H => "KEY_H",
            Self::KEY_J => "KEY_J",
            Self::KEY_K => "KEY_K",
            Self::KEY_L => "KEY_L",
            Self::KEY_SEMICOLON => "KEY_SEMICOLON",
            Self::KEY_APOSTROPHE => "KEY_APOSTROPHE",
            Self::KEY_GRAVE => "KEY_GRAVE",
            Self::KEY_LEFTSHIFT => "KEY_LEFTSHIFT",
            Self::KEY_BACKSLASH => "KEY_BACKSLASH",
            Self::KEY_Z => "KEY_Z",
            Self::KEY_X => "KEY_X",
            Self::KEY_C => "KEY_C",
            Self::KEY_V => "KEY_V",
            Self::KEY_B => "KEY_B",
            Self::KEY_N => "KEY_N",
            Self::KEY_M => "KEY_M",
            Self::KEY_COMMA => "KEY_COMMA",
            Self::KEY_DOT => "KEY_DOT",
            Self::KEY_SLASH => "KEY_SLASH",
            Self::KEY_RIGHTSHIFT => "KEY_RIGHTSHIFT",
            Self::KEY_KPASTERISK => "KEY_KPASTERISK",
            Self::KEY_LEFTALT => "KEY_LEFTALT",
            Self::KEY_SPACE => "KEY_SPACE",
            Self::KEY_CAPSLOCK => "KEY_CAPSLOCK",
            Self::KEY_F1 => "KEY_F1",
            Self::KEY_F2 => "KEY_F2",
            Self::KEY_F3 => "KEY_F3",
            Self::KEY_F4 => "KEY_F4",
            Self::KEY_F5 => "KEY_F5",
            Self::KEY_F6 => "KEY_F6",
            Self::KEY_F7 => "KEY_F7",
            Self::KEY_F8 => "KEY_F8",
            Self::KEY_F9 => "KEY_F9",
            Self::KEY_F10 => "KEY_F10",
            Self::KEY_NUMLOCK => "KEY_NUMLOCK",
            Self::KEY_SCROLLLOCK => "KEY_SCROLLLOCK",
            Self::KEY_KP7 => "KEY_KP7",
            Self::KEY_KP8 => "KEY_KP8",
            Self::KEY_KP9 => "KEY_KP9",
            Self::KEY_KPMINUS => "KEY_KPMINUS",
            Self::KEY_KP4 => "KEY_KP4",
            Self::KEY_KP5 => "KEY_KP5",
            Self::KEY_KP6 => "KEY_KP6",
            Self::KEY_KPPLUS => "KEY_KPPLUS",
            Self::KEY_KP1 => "KEY_KP1",
            Self::KEY_KP2 => "KEY_KP2",
            Self::KEY_KP3 => "KEY_KP3",
            Self::KEY_KP0 => "KEY_KP0",
            Self::KEY_KPDOT => "KEY_KPDOT",
            Self::KEY_ZENKAKUHANKAKU => "KEY_ZENKAKUHANKAKU",
            Self::KEY_102ND => "KEY_102ND",
            Self::KEY_F11 => "KEY_F11",
            Self::KEY_F12 => "KEY_F12",
            Self::KEY_RO => "KEY_RO",
            Self::KEY_KATAKANA => "KEY_KATAKANA",
            Self::KEY_HIRAGANA => "KEY_HIRAGANA",
            Self::KEY_HENKAN => "KEY_HENKAN",
            Self::KEY_KATAKANAHIRAGANA => "KEY_KATAKANAHIRAGANA",
            Self::KEY_MUHENKAN => "KEY_MUHENKAN",
            Self::KEY_KPJPCOMMA => "KEY_KPJPCOMMA",
            Self::KEY_KPENTER => "KEY_KPENTER",
            Self::KEY_RIGHTCTRL => "KEY_RIGHTCTRL",
            Self::KEY_KPSLASH => "KEY_KPSLASH",
            Self::KEY_SYSRQ => "KEY_SYSRQ",
            Self::KEY_RIGHTALT => "KEY_RIGHTALT",
            Self::KEY_LINEFEED => "KEY_LINEFEED",
            Self::KEY_HOME => "KEY_HOME",
            Self::KEY_UP => "KEY_UP",
            Self::KEY_PAGEUP => "KEY_PAGEUP",
            Self::KEY_LEFT => "KEY_LEFT",
            Self::KEY_RIGHT => "KEY_RIGHT",
            Self::KEY_END => "KEY_END",
            Self::KEY_DOWN => "KEY_DOWN",
            Self::KEY_PAGEDOWN => "KEY_PAGEDOWN",
            Self::KEY_INSERT => "KEY_INSERT",
            Self::KEY_DELETE => "KEY_DELETE",
            Self::KEY_MACRO => "KEY_MACRO",
            Self::KEY_MUTE => "KEY_MUTE",
            Self::KEY_VOLUMEDOWN => "KEY_VOLUMEDOWN",
            Self::KEY_VOLUMEUP => "KEY_VOLUMEUP",
            Self::KEY_POWER => "KEY_POWER",
            Self::KEY_KPEQUAL => "KEY_KPEQUAL",
            Self::KEY_KPPLUSMINUS => "KEY_KPPLUSMINUS",
            Self::KEY_PAUSE => "KEY_PAUSE",
            Self::KEY_SCALE => "KEY_SCALE",
            Self::KEY_KPCOMMA => "KEY_KPCOMMA",
            Self::KEY_HANGEUL => "KEY_HANGEUL,KEY_HANGUEL",
            Self::KEY_HANJA => "KEY_HANJA",
            Self::KEY_YEN => "KEY_YEN",
            Self::KEY_LEFTMETA => "KEY_LEFTMETA",
            Self::KEY_RIGHTMETA => "KEY_RIGHTMETA",
            Self::KEY_COMPOSE => "KEY_COMPOSE",
            Self::KEY_STOP => "KEY_STOP",
            Self::KEY_AGAIN => "KEY_AGAIN",
            Self::KEY_PROPS => "KEY_PROPS",
            Self::KEY_UNDO => "KEY_UNDO",
            Self::KEY_FRONT => "KEY_FRONT",
            Self::KEY_COPY => "KEY_COPY",
            Self::KEY_OPEN => "KEY_OPEN",
            Self::KEY_PASTE => "KEY_PASTE",
            Self::KEY_FIND => "KEY_FIND",
            Self::KEY_CUT => "KEY_CUT",
            Self::KEY_HELP => "KEY_HELP",
            Self::KEY_MENU => "KEY_MENU",
            Self::KEY_CALC => "KEY_CALC",
            Self::KEY_SETUP => "KEY_SETUP",
            Self::KEY_SLEEP => "KEY_SLEEP",
            Self::KEY_WAKEUP => "KEY_WAKEUP",
            Self::KEY_FILE => "KEY_FILE",
            Self::KEY_SENDFILE => "KEY_SENDFILE",
            Self::KEY_DELETEFILE => "KEY_DELETEFILE",
            Self::KEY_XFER => "KEY_XFER",
            Self::KEY_PROG1 => "KEY_PROG1",
            Self::KEY_PROG2 => "KEY_PROG2",
            Self::KEY_WWW => "KEY_WWW",
            Self::KEY_MSDOS => "KEY_MSDOS",
            Self::KEY_COFFEE => "KEY_COFFEE,KEY_SCREENLOCK",
            Self::KEY_ROTATE_DISPLAY => "KEY_ROTATE_DISPLAY,KEY_DIRECTION",
            Self::KEY_CYCLEWINDOWS => "KEY_CYCLEWINDOWS",
            Self::KEY_MAIL => "KEY_MAIL",
            Self::KEY_BOOKMARKS => "KEY_BOOKMARKS",
            Self::KEY_COMPUTER => "KEY_COMPUTER",
            Self::KEY_BACK => "KEY_BACK",
            Self::KEY_FORWARD => "KEY_FORWARD",
            Self::KEY_CLOSECD => "KEY_CLOSECD",
            Self::KEY_EJECTCD => "KEY_EJECTCD",
            Self::KEY_EJECTCLOSECD => "KEY_EJECTCLOSECD",
            Self::KEY_NEXTSONG => "KEY_NEXTSONG",
            Self::KEY_PLAYPAUSE => "KEY_PLAYPAUSE",
            Self::KEY_PREVIOUSSONG => "KEY_PREVIOUSSONG",
            Self::KEY_STOPCD => "KEY_STOPCD",
            Self::KEY_RECORD => "KEY_RECORD",
            Self::KEY_REWIND => "KEY_REWIND",
            Self::KEY_PHONE => "KEY_PHONE",
            Self::KEY_ISO => "KEY_ISO",
            Self::KEY_CONFIG => "KEY_CONFIG",
            Self::KEY_HOMEPAGE => "KEY_HOMEPAGE",
            Self::KEY_REFRESH => "KEY_REFRESH",
            Self::KEY_EXIT => "KEY_EXIT",
            Self::KEY_MOVE => "KEY_MOVE",
            Self::KEY_EDIT => "KEY_EDIT",
            Self::KEY_SCROLLUP => "KEY_SCROLLUP",
            Self::KEY_SCROLLDOWN => "KEY_SCROLLDOWN",
            Self::KEY_KPLEFTPAREN => "KEY_KPLEFTPAREN",
            Self::KEY_KPRIGHTPAREN => "KEY_KPRIGHTPAREN",
            Self::KEY_NEW => "KEY_NEW",
            Self::KEY_REDO => "KEY_REDO",
            Self::KEY_F13 => "KEY_F13",
            Self::KEY_F14 => "KEY_F14",
            Self::KEY_F15 => "KEY_F15",
            Self::KEY_F16 => "KEY_F16",
            Self::KEY_F17 => "KEY_F17",
            Self::KEY_F18 => "KEY_F18",
            Self::KEY_F19 => "KEY_F19",
            Self::KEY_F20 => "KEY_F20",
            Self::KEY_F21 => "KEY_F21",
            Self::KEY_F22 => "KEY_F22",
            Self::KEY_F23 => "KEY_F23",
            Self::KEY_F24 => "KEY_F24",
            Self::KEY_PLAYCD => "KEY_PLAYCD",
            Self::KEY_PAUSECD => "KEY_PAUSECD",
            Self::KEY_PROG3 => "KEY_PROG3",
            Self::KEY_PROG4 => "KEY_PROG4",
            Self::KEY_ALL_APPLICATIONS => "KEY_ALL_APPLICATIONS,KEY_DASHBOARD",
            Self::KEY_SUSPEND => "KEY_SUSPEND",
            Self::KEY_CLOSE => "KEY_CLOSE",
            Self::KEY_PLAY => "KEY_PLAY",
            Self::KEY_FASTFORWARD => "KEY_FASTFORWARD",
            Self::KEY_BASSBOOST => "KEY_BASSBOOST",
            Self::KEY_PRINT => "KEY_PRINT",
            Self::KEY_HP => "KEY_HP",
            Self::KEY_CAMERA => "KEY_CAMERA",
            Self::KEY_SOUND => "KEY_SOUND",
            Self::KEY_QUESTION => "KEY_QUESTION",
            Self::KEY_EMAIL => "KEY_EMAIL",
            Self::KEY_CHAT => "KEY_CHAT",
            Self::KEY_SEARCH => "KEY_SEARCH",
            Self::KEY_CONNECT => "KEY_CONNECT",
            Self::KEY_FINANCE => "KEY_FINANCE",
            Self::KEY_SPORT => "KEY_SPORT",
            Self::KEY_SHOP => "KEY_SHOP",
            Self::KEY_ALTERASE => "KEY_ALTERASE",
            Self::KEY_CANCEL => "KEY_CANCEL",
            Self::KEY_BRIGHTNESSDOWN => "KEY_BRIGHTNESSDOWN",
            Self::KEY_BRIGHTNESSUP => "KEY_BRIGHTNESSUP",
            Self::KEY_MEDIA => "KEY_MEDIA",
            Self::KEY_SWITCHVIDEOMODE => "KEY_SWITCHVIDEOMODE",
            Self::KEY_KBDILLUMTOGGLE => "KEY_KBDILLUMTOGGLE",
            Self::KEY_KBDILLUMDOWN => "KEY_KBDILLUMDOWN",
            Self::KEY_KBDILLUMUP => "KEY_KBDILLUMUP",
            Self::KEY_SEND => "KEY_SEND",
            Self::KEY_REPLY => "KEY_REPLY",
            Self::KEY_FORWARDMAIL => "KEY_FORWARDMAIL",
            Self::KEY_SAVE => "KEY_SAVE",
            Self::KEY_DOCUMENTS => "KEY_DOCUMENTS",
            Self::KEY_BATTERY => "KEY_BATTERY",
            Self::KEY_BLUETOOTH => "KEY_BLUETOOTH",
            Self::KEY_WLAN => "KEY_WLAN",
            Self::KEY_UWB => "KEY_UWB",
            Self::KEY_UNKNOWN => "KEY_UNKNOWN",
            Self::KEY_VIDEO_NEXT => "KEY_VIDEO_NEXT",
            Self::KEY_VIDEO_PREV => "KEY_VIDEO_PREV",
            Self::KEY_BRIGHTNESS_CYCLE => "KEY_BRIGHTNESS_CYCLE",
            Self::KEY_BRIGHTNESS_AUTO => "KEY_BRIGHTNESS_AUTO,KEY_BRIGHTNESS_ZERO",
            Self::KEY_DISPLAY_OFF => "KEY_DISPLAY_OFF",
            Self::KEY_WWAN => "KEY_WWAN,KEY_WIMAX",
            Self::KEY_RFKILL => "KEY_RFKILL",
            Self::KEY_MICMUTE => "KEY_MICMUTE",
            Self::BTN_MISC => "BTN_MISC,BTN_0",
            Self::BTN_1 => "BTN_1",
            Self::BTN_2 => "BTN_2",
            Self::BTN_3 => "BTN_3",
            Self::BTN_4 => "BTN_4",
            Self::BTN_5 => "BTN_5",
            Self::BTN_6 => "BTN_6",
            Self::BTN_7 => "BTN_7",
            Self::BTN_8 => "BTN_8",
            Self::BTN_9 => "BTN_9",
            Self::BTN_MOUSE => "BTN_MOUSE,BTN_LEFT",
            Self::BTN_RIGHT => "BTN_RIGHT",
            Self::BTN_MIDDLE => "BTN_MIDDLE",
            Self::BTN_SIDE => "BTN_SIDE",
            Self::BTN_EXTRA => "BTN_EXTRA",
            Self::BTN_FORWARD => "BTN_FORWARD",
            Self::BTN_BACK => "BTN_BACK",
            Self::BTN_TASK => "BTN_TASK",
            Self::BTN_JOYSTICK => "BTN_JOYSTICK,BTN_TRIGGER",
            Self::BTN_THUMB => "BTN_THUMB",
            Self::BTN_THUMB2 => "BTN_THUMB2",
            Self::BTN_TOP => "BTN_TOP",
            Self::BTN_TOP2 => "BTN_TOP2",
            Self::BTN_PINKIE => "BTN_PINKIE",
            Self::BTN_BASE => "BTN_BASE",
            Self::BTN_BASE2 => "BTN_BASE2",
            Self::BTN_BASE3 => "BTN_BASE3",
            Self::BTN_BASE4 => "BTN_BASE4",
            Self::BTN_BASE5 => "BTN_BASE5",
            Self::BTN_BASE6 => "BTN_BASE6",
            Self::BTN_DEAD => "BTN_DEAD",
            Self::BTN_GAMEPAD => "BTN_GAMEPAD,BTN_SOUTH,BTN_A",
            Self::BTN_EAST => "BTN_EAST,BTN_B",
            Self::BTN_C => "BTN_C",
            Self::BTN_NORTH => "BTN_NORTH,BTN_X",
            Self::BTN_WEST => "BTN_WEST,BTN_Y",
            Self::BTN_Z => "BTN_Z",
            Self::BTN_TL => "BTN_TL",
            Self::BTN_TR => "BTN_TR",
            Self::BTN_TL2 => "BTN_TL2",
            Self::BTN_TR2 => "BTN_TR2",
            Self::BTN_SELECT => "BTN_SELECT",
            Self::BTN_START => "BTN_START",
            Self::BTN_MODE => "BTN_MODE",
            Self::BTN_THUMBL => "BTN_THUMBL",
            Self::BTN_THUMBR => "BTN_THUMBR",
            Self::BTN_DIGI => "BTN_DIGI,BTN_TOOL_PEN",
            Self::BTN_TOOL_RUBBER => "BTN_TOOL_RUBBER",
            Self::BTN_TOOL_BRUSH => "BTN_TOOL_BRUSH",
            Self::BTN_TOOL_PENCIL => "BTN_TOOL_PENCIL",
            Self::BTN_TOOL_AIRBRUSH => "BTN_TOOL_AIRBRUSH",
            Self::BTN_TOOL_FINGER => "BTN_TOOL_FINGER",
            Self::BTN_TOOL_MOUSE => "BTN_TOOL_MOUSE",
            Self::BTN_TOOL_LENS => "BTN_TOOL_LENS",
            Self::BTN_TOOL_QUINTTAP => "BTN_TOOL_QUINTTAP",
            Self::BTN_STYLUS3 => "BTN_STYLUS3",
            Self::BTN_TOUCH => "BTN_TOUCH",
            Self::BTN_STYLUS => "BTN_STYLUS",
            Self::BTN_STYLUS2 => "BTN_STYLUS2",
            Self::BTN_TOOL_DOUBLETAP => "BTN_TOOL_DOUBLETAP",
            Self::BTN_TOOL_TRIPLETAP => "BTN_TOOL_TRIPLETAP",
            Self::BTN_TOOL_QUADTAP => "BTN_TOOL_QUADTAP",
            Self::BTN_WHEEL => "BTN_WHEEL,BTN_GEAR_DOWN",
            Self::BTN_GEAR_UP => "BTN_GEAR_UP",
            Self::KEY_OK => "KEY_OK",
            Self::KEY_SELECT => "KEY_SELECT",
            Self::KEY_GOTO => "KEY_GOTO",
            Self::KEY_CLEAR => "KEY_CLEAR",
            Self::KEY_POWER2 => "KEY_POWER2",
            Self::KEY_OPTION => "KEY_OPTION",
            Self::KEY_INFO => "KEY_INFO",
            Self::KEY_TIME => "KEY_TIME",
            Self::KEY_VENDOR => "KEY_VENDOR",
            Self::KEY_ARCHIVE => "KEY_ARCHIVE",
            Self::KEY_PROGRAM => "KEY_PROGRAM",
            Self::KEY_CHANNEL => "KEY_CHANNEL",
            Self::KEY_FAVORITES => "KEY_FAVORITES",
            Self::KEY_EPG => "KEY_EPG",
            Self::KEY_PVR => "KEY_PVR",
            Self::KEY_MHP => "KEY_MHP",
            Self::KEY_LANGUAGE => "KEY_LANGUAGE",
            Self::KEY_TITLE => "KEY_TITLE",
            Self::KEY_SUBTITLE => "KEY_SUBTITLE",
            Self::KEY_ANGLE => "KEY_ANGLE",
            Self::KEY_FULL_SCREEN => "KEY_FULL_SCREEN,KEY_ZOOM",
            Self::KEY_MODE => "KEY_MODE",
            Self::KEY_KEYBOARD => "KEY_KEYBOARD",
            Self::KEY_ASPECT_RATIO => "KEY_ASPECT_RATIO,KEY_SCREEN",
            Self::KEY_PC => "KEY_PC",
            Self::KEY_TV => "KEY_TV",
            Self::KEY_TV2 => "KEY_TV2",
            Self::KEY_VCR => "KEY_VCR",
            Self::KEY_VCR2 => "KEY_VCR2",
            Self::KEY_SAT => "KEY_SAT",
            Self::KEY_SAT2 => "KEY_SAT2",
            Self::KEY_CD => "KEY_CD",
            Self::KEY_TAPE => "KEY_TAPE",
            Self::KEY_RADIO => "KEY_RADIO",
            Self::KEY_TUNER => "KEY_TUNER",
            Self::KEY_PLAYER => "KEY_PLAYER",
            Self::KEY_TEXT => "KEY_TEXT",
            Self::KEY_DVD => "KEY_DVD",
            Self::KEY_AUX => "KEY_AUX",
            Self::KEY_MP3 => "KEY_MP3",
            Self::KEY_AUDIO => "KEY_AUDIO",
            Self::KEY_VIDEO => "KEY_VIDEO",
            Self::KEY_DIRECTORY => "KEY_DIRECTORY",
            Self::KEY_LIST => "KEY_LIST",
            Self::KEY_MEMO => "KEY_MEMO",
            Self::KEY_CALENDAR => "KEY_CALENDAR",
            Self::KEY_RED => "KEY_RED",
            Self::KEY_GREEN => "KEY_GREEN",
            Self::KEY_YELLOW => "KEY_YELLOW",
            Self::KEY_BLUE => "KEY_BLUE",
            Self::KEY_CHANNELUP => "KEY_CHANNELUP",
            Self::KEY_CHANNELDOWN => "KEY_CHANNELDOWN",
            Self::KEY_FIRST => "KEY_FIRST",
            Self::KEY_LAST => "KEY_LAST",
            Self::KEY_AB => "KEY_AB",
            Self::KEY_NEXT => "KEY_NEXT",
            Self::KEY_RESTART => "KEY_RESTART",
            Self::KEY_SLOW => "KEY_SLOW",
            Self::KEY_SHUFFLE => "KEY_SHUFFLE",
            Self::KEY_BREAK => "KEY_BREAK",
            Self::KEY_PREVIOUS => "KEY_PREVIOUS",
            Self::KEY_DIGITS => "KEY_DIGITS",
            Self::KEY_TEEN => "KEY_TEEN",
            Self::KEY_TWEN => "KEY_TWEN",
            Self::KEY_VIDEOPHONE => "KEY_VIDEOPHONE",
            Self::KEY_GAMES => "KEY_GAMES",
            Self::KEY_ZOOMIN => "KEY_ZOOMIN",
            Self::KEY_ZOOMOUT => "KEY_ZOOMOUT",
            Self::KEY_ZOOMRESET => "KEY_ZOOMRESET",
            Self::KEY_WORDPROCESSOR => "KEY_WORDPROCESSOR",
            Self::KEY_EDITOR => "KEY_EDITOR",
            Self::KEY_SPREADSHEET => "KEY_SPREADSHEET",
            Self::KEY_GRAPHICSEDITOR => "KEY_GRAPHICSEDITOR",
            Self::KEY_PRESENTATION => "KEY_PRESENTATION",
            Self::KEY_DATABASE => "KEY_DATABASE",
            Self::KEY_NEWS => "KEY_NEWS",
            Self::KEY_VOICEMAIL => "KEY_VOICEMAIL",
            Self::KEY_ADDRESSBOOK => "KEY_ADDRESSBOOK",
            Self::KEY_MESSENGER => "KEY_MESSENGER",
            Self::KEY_DISPLAYTOGGLE => "KEY_DISPLAYTOGGLE,KEY_BRIGHTNESS_TOGGLE",
            Self::KEY_SPELLCHECK => "KEY_SPELLCHECK",
            Self::KEY_LOGOFF => "KEY_LOGOFF",
            Self::KEY_DOLLAR => "KEY_DOLLAR",
            Self::KEY_EURO => "KEY_EURO",
            Self::KEY_FRAMEBACK => "KEY_FRAMEBACK",
            Self::KEY_FRAMEFORWARD => "KEY_FRAMEFORWARD",
            Self::KEY_CONTEXT_MENU => "KEY_CONTEXT_MENU",
            Self::KEY_MEDIA_REPEAT => "KEY_MEDIA_REPEAT",
            Self::KEY_10CHANNELSUP => "KEY_10CHANNELSUP",
            Self::KEY_10CHANNELSDOWN => "KEY_10CHANNELSDOWN",
            Self::KEY_IMAGES => "KEY_IMAGES",
            Self::KEY_NOTIFICATION_CENTER => "KEY_NOTIFICATION_CENTER",
            Self::KEY_PICKUP_PHONE => "KEY_PICKUP_PHONE",
            Self::KEY_HANGUP_PHONE => "KEY_HANGUP_PHONE",
            Self::KEY_LINK_PHONE => "KEY_LINK_PHONE",
            Self::KEY_DEL_EOL => "KEY_DEL_EOL",
            Self::KEY_DEL_EOS => "KEY_DEL_EOS",
            Self::KEY_INS_LINE => "KEY_INS_LINE",
            Self::KEY_DEL_LINE => "KEY_DEL_LINE",
            Self::KEY_FN => "KEY_FN",
            Self::KEY_FN_ESC => "KEY_FN_ESC",
            Self::KEY_FN_F1 => "KEY_FN_F1",
            Self::KEY_FN_F2 => "KEY_FN_F2",
            Self::KEY_FN_F3 => "KEY_FN_F3",
            Self::KEY_FN_F4 => "KEY_FN_F4",
            Self::KEY_FN_F5 => "KEY_FN_F5",
            Self::KEY_FN_F6 => "KEY_FN_F6",
            Self::KEY_FN_F7 => "KEY_FN_F7",
            Self::KEY_FN_F8 => "KEY_FN_F8",
            Self::KEY_FN_F9 => "KEY_FN_F9",
            Self::KEY_FN_F10 => "KEY_FN_F10",
            Self::KEY_FN_F11 => "KEY_FN_F11",
            Self::KEY_FN_F12 => "KEY_FN_F12",
            Self::KEY_FN_1 => "KEY_FN_1",
            Self::KEY_FN_2 => "KEY_FN_2",
            Self::KEY_FN_D => "KEY_FN_D",
            Self::KEY_FN_E => "KEY_FN_E",
            Self::KEY_FN_F => "KEY_FN_F",
            Self::KEY_FN_S => "KEY_FN_S",
            Self::KEY_FN_B => "KEY_FN_B",
            Self::KEY_FN_RIGHT_SHIFT => "KEY_FN_RIGHT_SHIFT",
            Self::KEY_BRL_DOT1 => "KEY_BRL_DOT1",
            Self::KEY_BRL_DOT2 => "KEY_BRL_DOT2",
            Self::KEY_BRL_DOT3 => "KEY_BRL_DOT3",
            Self::KEY_BRL_DOT4 => "KEY_BRL_DOT4",
            Self::KEY_BRL_DOT5 => "KEY_BRL_DOT5",
            Self::KEY_BRL_DOT6 => "KEY_BRL_DOT6",
            Self::KEY_BRL_DOT7 => "KEY_BRL_DOT7",
            Self::KEY_BRL_DOT8 => "KEY_BRL_DOT8",
            Self::KEY_BRL_DOT9 => "KEY_BRL_DOT9",
            Self::KEY_BRL_DOT10 => "KEY_BRL_DOT10",
            Self::KEY_NUMERIC_0 => "KEY_NUMERIC_0",
            Self::KEY_NUMERIC_1 => "KEY_NUMERIC_1",
            Self::KEY_NUMERIC_2 => "KEY_NUMERIC_2",
            Self::KEY_NUMERIC_3 => "KEY_NUMERIC_3",
            Self::KEY_NUMERIC_4 => "KEY_NUMERIC_4",
            Self::KEY_NUMERIC_5 => "KEY_NUMERIC_5",
            Self::KEY_NUMERIC_6 => "KEY_NUMERIC_6",
            Self::KEY_NUMERIC_7 => "KEY_NUMERIC_7",
            Self::KEY_NUMERIC_8 => "KEY_NUMERIC_8",
            Self::KEY_NUMERIC_9 => "KEY_NUMERIC_9",
            Self::KEY_NUMERIC_STAR => "KEY_NUMERIC_STAR",
            Self::KEY_NUMERIC_POUND => "KEY_NUMERIC_POUND",
            Self::KEY_NUMERIC_A => "KEY_NUMERIC_A",
            Self::KEY_NUMERIC_B => "KEY_NUMERIC_B",
            Self::KEY_NUMERIC_C => "KEY_NUMERIC_C",
            Self::KEY_NUMERIC_D => "KEY_NUMERIC_D",
            Self::KEY_CAMERA_FOCUS => "KEY_CAMERA_FOCUS",
            Self::KEY_WPS_BUTTON => "KEY_WPS_BUTTON",
            Self::KEY_TOUCHPAD_TOGGLE => "KEY_TOUCHPAD_TOGGLE",
            Self::KEY_TOUCHPAD_ON => "KEY_TOUCHPAD_ON",
            Self::KEY_TOUCHPAD_OFF => "KEY_TOUCHPAD_OFF",
            Self::KEY_CAMERA_ZOOMIN => "KEY_CAMERA_ZOOMIN",
            Self::KEY_CAMERA_ZOOMOUT => "KEY_CAMERA_ZOOMOUT",
            Self::KEY_CAMERA_UP => "KEY_CAMERA_UP",
            Self::KEY_CAMERA_DOWN => "KEY_CAMERA_DOWN",
            Self::KEY_CAMERA_LEFT => "KEY_CAMERA_LEFT",
            Self::KEY_CAMERA_RIGHT => "KEY_CAMERA_RIGHT",
            Self::KEY_ATTENDANT_ON => "KEY_ATTENDANT_ON",
            Self::KEY_ATTENDANT_OFF => "KEY_ATTENDANT_OFF",
            Self::KEY_ATTENDANT_TOGGLE => "KEY_ATTENDANT_TOGGLE",
            Self::KEY_LIGHTS_TOGGLE => "KEY_LIGHTS_TOGGLE",
            Self::BTN_DPAD_UP => "BTN_DPAD_UP",
            Self::BTN_DPAD_DOWN => "BTN_DPAD_DOWN",
            Self::BTN_DPAD_LEFT => "BTN_DPAD_LEFT",
            Self::BTN_DPAD_RIGHT => "BTN_DPAD_RIGHT",
            Self::BTN_GRIPL => "BTN_GRIPL",
            Self::BTN_GRIPR => "BTN_GRIPR",
            Self::BTN_GRIPL2 => "BTN_GRIPL2",
            Self::BTN_GRIPR2 => "BTN_GRIPR2",
            Self::KEY_ALS_TOGGLE => "KEY_ALS_TOGGLE",
            Self::KEY_ROTATE_LOCK_TOGGLE => "KEY_ROTATE_LOCK_TOGGLE",
            Self::KEY_REFRESH_RATE_TOGGLE => "KEY_REFRESH_RATE_TOGGLE",
            Self::KEY_BUTTONCONFIG => "KEY_BUTTONCONFIG",
            Self::KEY_TASKMANAGER => "KEY_TASKMANAGER",
            Self::KEY_JOURNAL => "KEY_JOURNAL",
            Self::KEY_CONTROLPANEL => "KEY_CONTROLPANEL",
            Self::KEY_APPSELECT => "KEY_APPSELECT",
            Self::KEY_SCREENSAVER => "KEY_SCREENSAVER",
            Self::KEY_VOICECOMMAND => "KEY_VOICECOMMAND",
            Self::KEY_ASSISTANT => "KEY_ASSISTANT",
            Self::KEY_KBD_LAYOUT_NEXT => "KEY_KBD_LAYOUT_NEXT",
            Self::KEY_EMOJI_PICKER => "KEY_EMOJI_PICKER",
            Self::KEY_DICTATE => "KEY_DICTATE",
            Self::KEY_CAMERA_ACCESS_ENABLE => "KEY_CAMERA_ACCESS_ENABLE",
            Self::KEY_CAMERA_ACCESS_DISABLE => "KEY_CAMERA_ACCESS_DISABLE",
            Self::KEY_CAMERA_ACCESS_TOGGLE => "KEY_CAMERA_ACCESS_TOGGLE",
            Self::KEY_ACCESSIBILITY => "KEY_ACCESSIBILITY",
            Self::KEY_DO_NOT_DISTURB => "KEY_DO_NOT_DISTURB",
            Self::KEY_BRIGHTNESS_MIN => "KEY_BRIGHTNESS_MIN",
            Self::KEY_BRIGHTNESS_MAX => "KEY_BRIGHTNESS_MAX",
            Self::KEY_EPRIVACY_SCREEN_ON => "KEY_EPRIVACY_SCREEN_ON",
            Self::KEY_EPRIVACY_SCREEN_OFF => "KEY_EPRIVACY_SCREEN_OFF",
            Self::KEY_ACTION_ON_SELECTION => "KEY_ACTION_ON_SELECTION",
            Self::KEY_CONTEXTUAL_INSERT => "KEY_CONTEXTUAL_INSERT",
            Self::KEY_CONTEXTUAL_QUERY => "KEY_CONTEXTUAL_QUERY",
            Self::KEY_KBDINPUTASSIST_PREV => "KEY_KBDINPUTASSIST_PREV",
            Self::KEY_KBDINPUTASSIST_NEXT => "KEY_KBDINPUTASSIST_NEXT",
            Self::KEY_KBDINPUTASSIST_PREVGROUP => "KEY_KBDINPUTASSIST_PREVGROUP",
            Self::KEY_KBDINPUTASSIST_NEXTGROUP => "KEY_KBDINPUTASSIST_NEXTGROUP",
            Self::KEY_KBDINPUTASSIST_ACCEPT => "KEY_KBDINPUTASSIST_ACCEPT",
            Self::KEY_KBDINPUTASSIST_CANCEL => "KEY_KBDINPUTASSIST_CANCEL",
            Self::KEY_RIGHT_UP => "KEY_RIGHT_UP",
            Self::KEY_RIGHT_DOWN => "KEY_RIGHT_DOWN",
            Self::KEY_LEFT_UP => "KEY_LEFT_UP",
            Self::KEY_LEFT_DOWN => "KEY_LEFT_DOWN",
            Self::KEY_ROOT_MENU => "KEY_ROOT_MENU",
            Self::KEY_MEDIA_TOP_MENU => "KEY_MEDIA_TOP_MENU",
            Self::KEY_NUMERIC_11 => "KEY_NUMERIC_11",
            Self::KEY_NUMERIC_12 => "KEY_NUMERIC_12",
            Self::KEY_AUDIO_DESC => "KEY_AUDIO_DESC",
            Self::KEY_3D_MODE => "KEY_3D_MODE",
            Self::KEY_NEXT_FAVORITE => "KEY_NEXT_FAVORITE",
            Self::KEY_STOP_RECORD => "KEY_STOP_RECORD",
            Self::KEY_PAUSE_RECORD => "KEY_PAUSE_RECORD",
            Self::KEY_VOD => "KEY_VOD",
            Self::KEY_UNMUTE => "KEY_UNMUTE",
            Self::KEY_FASTREVERSE => "KEY_FASTREVERSE",
            Self::KEY_SLOWREVERSE => "KEY_SLOWREVERSE",
            Self::KEY_DATA => "KEY_DATA",
            Self::KEY_ONSCREEN_KEYBOARD => "KEY_ONSCREEN_KEYBOARD",
            Self::KEY_PRIVACY_SCREEN_TOGGLE => "KEY_PRIVACY_SCREEN_TOGGLE",
            Self::KEY_SELECTIVE_SCREENSHOT => "KEY_SELECTIVE_SCREENSHOT",
            Self::KEY_NEXT_ELEMENT => "KEY_NEXT_ELEMENT",
            Self::KEY_PREVIOUS_ELEMENT => "KEY_PREVIOUS_ELEMENT",
            Self::KEY_AUTOPILOT_ENGAGE_TOGGLE => "KEY_AUTOPILOT_ENGAGE_TOGGLE",
            Self::KEY_MARK_WAYPOINT => "KEY_MARK_WAYPOINT",
            Self::KEY_SOS => "KEY_SOS",
            Self::KEY_NAV_CHART => "KEY_NAV_CHART",
            Self::KEY_FISHING_CHART => "KEY_FISHING_CHART",
            Self::KEY_SINGLE_RANGE_RADAR => "KEY_SINGLE_RANGE_RADAR",
            Self::KEY_DUAL_RANGE_RADAR => "KEY_DUAL_RANGE_RADAR",
            Self::KEY_RADAR_OVERLAY => "KEY_RADAR_OVERLAY",
            Self::KEY_TRADITIONAL_SONAR => "KEY_TRADITIONAL_SONAR",
            Self::KEY_CLEARVU_SONAR => "KEY_CLEARVU_SONAR",
            Self::KEY_SIDEVU_SONAR => "KEY_SIDEVU_SONAR",
            Self::KEY_NAV_INFO => "KEY_NAV_INFO",
            Self::KEY_BRIGHTNESS_MENU => "KEY_BRIGHTNESS_MENU",
            Self::KEY_MACRO1 => "KEY_MACRO1",
            Self::KEY_MACRO2 => "KEY_MACRO2",
            Self::KEY_MACRO3 => "KEY_MACRO3",
            Self::KEY_MACRO4 => "KEY_MACRO4",
            Self::KEY_MACRO5 => "KEY_MACRO5",
            Self::KEY_MACRO6 => "KEY_MACRO6",
            Self::KEY_MACRO7 => "KEY_MACRO7",
            Self::KEY_MACRO8 => "KEY_MACRO8",
            Self::KEY_MACRO9 => "KEY_MACRO9",
            Self::KEY_MACRO10 => "KEY_MACRO10",
            Self::KEY_MACRO11 => "KEY_MACRO11",
            Self::KEY_MACRO12 => "KEY_MACRO12",
            Self::KEY_MACRO13 => "KEY_MACRO13",
            Self::KEY_MACRO14 => "KEY_MACRO14",
            Self::KEY_MACRO15 => "KEY_MACRO15",
            Self::KEY_MACRO16 => "KEY_MACRO16",
            Self::KEY_MACRO17 => "KEY_MACRO17",
            Self::KEY_MACRO18 => "KEY_MACRO18",
            Self::KEY_MACRO19 => "KEY_MACRO19",
            Self::KEY_MACRO20 => "KEY_MACRO20",
            Self::KEY_MACRO21 => "KEY_MACRO21",
            Self::KEY_MACRO22 => "KEY_MACRO22",
            Self::KEY_MACRO23 => "KEY_MACRO23",
            Self::KEY_MACRO24 => "KEY_MACRO24",
            Self::KEY_MACRO25 => "KEY_MACRO25",
            Self::KEY_MACRO26 => "KEY_MACRO26",
            Self::KEY_MACRO27 => "KEY_MACRO27",
            Self::KEY_MACRO28 => "KEY_MACRO28",
            Self::KEY_MACRO29 => "KEY_MACRO29",
            Self::KEY_MACRO30 => "KEY_MACRO30",
            Self::KEY_MACRO_RECORD_START => "KEY_MACRO_RECORD_START",
            Self::KEY_MACRO_RECORD_STOP => "KEY_MACRO_RECORD_STOP",
            Self::KEY_MACRO_PRESET_CYCLE => "KEY_MACRO_PRESET_CYCLE",
            Self::KEY_MACRO_PRESET1 => "KEY_MACRO_PRESET1",
            Self::KEY_MACRO_PRESET2 => "KEY_MACRO_PRESET2",
            Self::KEY_MACRO_PRESET3 => "KEY_MACRO_PRESET3",
            Self::KEY_KBD_LCD_MENU1 => "KEY_KBD_LCD_MENU1",
            Self::KEY_KBD_LCD_MENU2 => "KEY_KBD_LCD_MENU2",
            Self::KEY_KBD_LCD_MENU3 => "KEY_KBD_LCD_MENU3",
            Self::KEY_KBD_LCD_MENU4 => "KEY_KBD_LCD_MENU4",
            Self::KEY_KBD_LCD_MENU5 => "KEY_KBD_LCD_MENU5",
            Self::KEY_PERFORMANCE => "KEY_PERFORMANCE",
            Self::BTN_TRIGGER_HAPPY => "BTN_TRIGGER_HAPPY,BTN_TRIGGER_HAPPY1",
            Self::BTN_TRIGGER_HAPPY2 => "BTN_TRIGGER_HAPPY2",
            Self::BTN_TRIGGER_HAPPY3 => "BTN_TRIGGER_HAPPY3",
            Self::BTN_TRIGGER_HAPPY4 => "BTN_TRIGGER_HAPPY4",
            Self::BTN_TRIGGER_HAPPY5 => "BTN_TRIGGER_HAPPY5",
            Self::BTN_TRIGGER_HAPPY6 => "BTN_TRIGGER_HAPPY6",
            Self::BTN_TRIGGER_HAPPY7 => "BTN_TRIGGER_HAPPY7",
            Self::BTN_TRIGGER_HAPPY8 => "BTN_TRIGGER_HAPPY8",
            Self::BTN_TRIGGER_HAPPY9 => "BTN_TRIGGER_HAPPY9",
            Self::BTN_TRIGGER_HAPPY10 => "BTN_TRIGGER_HAPPY10",
            Self::BTN_TRIGGER_HAPPY11 => "BTN_TRIGGER_HAPPY11",
            Self::BTN_TRIGGER_HAPPY12 => "BTN_TRIGGER_HAPPY12",
            Self::BTN_TRIGGER_HAPPY13 => "BTN_TRIGGER_HAPPY13",
            Self::BTN_TRIGGER_HAPPY14 => "BTN_TRIGGER_HAPPY14",
            Self::BTN_TRIGGER_HAPPY15 => "BTN_TRIGGER_HAPPY15",
            Self::BTN_TRIGGER_HAPPY16 => "BTN_TRIGGER_HAPPY16",
            Self::BTN_TRIGGER_HAPPY17 => "BTN_TRIGGER_HAPPY17",
            Self::BTN_TRIGGER_HAPPY18 => "BTN_TRIGGER_HAPPY18",
            Self::BTN_TRIGGER_HAPPY19 => "BTN_TRIGGER_HAPPY19",
            Self::BTN_TRIGGER_HAPPY20 => "BTN_TRIGGER_HAPPY20",
            Self::BTN_TRIGGER_HAPPY21 => "BTN_TRIGGER_HAPPY21",
            Self::BTN_TRIGGER_HAPPY22 => "BTN_TRIGGER_HAPPY22",
            Self::BTN_TRIGGER_HAPPY23 => "BTN_TRIGGER_HAPPY23",
            Self::BTN_TRIGGER_HAPPY24 => "BTN_TRIGGER_HAPPY24",
            Self::BTN_TRIGGER_HAPPY25 => "BTN_TRIGGER_HAPPY25",
            Self::BTN_TRIGGER_HAPPY26 => "BTN_TRIGGER_HAPPY26",
            Self::BTN_TRIGGER_HAPPY27 => "BTN_TRIGGER_HAPPY27",
            Self::BTN_TRIGGER_HAPPY28 => "BTN_TRIGGER_HAPPY28",
            Self::BTN_TRIGGER_HAPPY29 => "BTN_TRIGGER_HAPPY29",
            Self::BTN_TRIGGER_HAPPY30 => "BTN_TRIGGER_HAPPY30",
            Self::BTN_TRIGGER_HAPPY31 => "BTN_TRIGGER_HAPPY31",
            Self::BTN_TRIGGER_HAPPY32 => "BTN_TRIGGER_HAPPY32",
            Self::BTN_TRIGGER_HAPPY33 => "BTN_TRIGGER_HAPPY33",
            Self::BTN_TRIGGER_HAPPY34 => "BTN_TRIGGER_HAPPY34",
            Self::BTN_TRIGGER_HAPPY35 => "BTN_TRIGGER_HAPPY35",
            Self::BTN_TRIGGER_HAPPY36 => "BTN_TRIGGER_HAPPY36",
            Self::BTN_TRIGGER_HAPPY37 => "BTN_TRIGGER_HAPPY37",
            Self::BTN_TRIGGER_HAPPY38 => "BTN_TRIGGER_HAPPY38",
            Self::BTN_TRIGGER_HAPPY39 => "BTN_TRIGGER_HAPPY39",
            Self::BTN_TRIGGER_HAPPY40 => "BTN_TRIGGER_HAPPY40",
        }
    }
}
