[package]
name = "jay-algorithms"
version = "0.4.0"
edition = "2024"
license = "GPL-3.0-only"
description = "Internal dependency of the Jay compositor"
repository = "https://github.com/mahkoh/jay"

[dependencies]
smallvec = { version = "1.8.0", features = ["const_generics", "const_new", "union"] }
uapi = "0.2.13"
static_assertions = "1.1.0"
bstr = { version = "1.13.1", default-features = false, features = ["std"] }
log = "0.4.33"
thiserror = "2.0.20"
rustc-hash = "2.1.3"

[dev-dependencies]
isnt = "0.2.0"
