name: docs

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Show env
      run: |
        uname -a
        ldd --version
    - name: Install
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
        rustup toolchain install nightly --allow-downgrade -c rustfmt
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Build
      run: |
        cd jay-config
        cargo doc
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './target/doc'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
