name: nix

concurrency:
  group: nix-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check
        run: nix flake check

      # Debug build with MSRV from Dev Shell in 7m57s
      # - name: Dev Shell
      #   run: nix develop -c cargo run -- version

      # Release Build with latest Rust in 11m5s
      # - name: Build
      #   run: nix build
